#include "orbital/OrbitalConstructRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
namespace elysium::orbital{namespace{
void normalize(OrbitalConstructState&s){std::sort(s.cargo.begin(),s.cargo.end(),[](const auto&a,const auto&b){return a.itemStableId<b.itemStableId;});std::vector<OrbitalCargoStack>o;for(auto x:s.cargo){if(!x.itemStableId||!x.contentId||!x.count)continue;if(!o.empty()&&o.back().itemStableId==x.itemStableId&&o.back().contentId==x.contentId)o.back().count=elysium::safe::saturatingAdd(o.back().count,x.count);else o.push_back(x);}s.cargo=std::move(o);}std::uint64_t used(const OrbitalConstructState&s){std::uint64_t n=0;for(auto&x:s.cargo)n=elysium::safe::saturatingAdd(n,x.count);return n;}OrbitalCargoStack* stack(OrbitalConstructState&s,std::uint64_t id){auto i=std::find_if(s.cargo.begin(),s.cargo.end(),[&](auto&x){return x.itemStableId==id;});return i==s.cargo.end()?nullptr:&*i;}}
bool OrbitalConstructRuntime::publish(OrbitalConstructDefinition d){if(!d.contentId||!std::isfinite(d.surveyRangeMultiplier)||d.surveyRangeMultiplier<0||!std::isfinite(d.maximumHull)||d.maximumHull<0)return false;definitions_[d.contentId]=d;return true;}
bool OrbitalConstructRuntime::create(OrbitalConstructState s){if(!s.stableId||!s.definitionContentId||!s.systemId||!s.orbitAddress||!definitions_.contains(s.definitionContentId)||constructs_.contains(s.stableId))return false;s.hull=elysium::safe::nonNegative(s.hull);normalize(s);if(used(s)>definitions_.at(s.definitionContentId).cargoCapacity)return false;constructs_[s.stableId]=std::move(s);return true;}
bool OrbitalConstructRuntime::setLifecycle(std::uint64_t id,ConstructLifecycle l){auto i=constructs_.find(id);if(i==constructs_.end())return false;i->second.lifecycle=l;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}bool OrbitalConstructRuntime::setPowered(std::uint64_t id,bool p){auto i=constructs_.find(id);if(i==constructs_.end())return false;i->second.powered=p;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}
const OrbitalConstructState* OrbitalConstructRuntime::find(std::uint64_t id)const{auto i=constructs_.find(id);return i==constructs_.end()?nullptr:&i->second;}
bool OrbitalConstructRuntime::operational(const OrbitalConstructState&s,OrbitalCapability c)const{auto d=definitions_.find(s.definitionContentId);return d!=definitions_.end()&&(d->second.capabilities&orbitalCapability(c))&&s.lifecycle==ConstructLifecycle::Active&&s.powered&&s.hull>0;}
SurveyRelayProjection OrbitalConstructRuntime::relay(std::uint64_t id)const{SurveyRelayProjection o;auto i=constructs_.find(id);if(i==constructs_.end()||!operational(i->second,OrbitalCapability::SurveyRelay))return o;o.available=true;o.rangeMultiplier=elysium::safe::nonNegative(definitions_.at(i->second.definitionContentId).surveyRangeMultiplier);o.constructStableId=id;return o;}
OrbitalServiceFailure OrbitalConstructRuntime::beginDepotTransfer(DepotTransferTransaction t){if(!t.stableId||!t.constructId||!t.externalEndpointId||!t.itemStableId||!t.contentId||!t.count)return OrbitalServiceFailure::InvalidRequest;if(depotTransactions_.contains(t.stableId))return OrbitalServiceFailure::DuplicateTransaction;auto i=constructs_.find(t.constructId);if(i==constructs_.end())return OrbitalServiceFailure::MissingConstruct;if(!operational(i->second,OrbitalCapability::CargoDepot))return i->second.powered?OrbitalServiceFailure::Inactive:OrbitalServiceFailure::Unpowered;auto&c=i->second;const auto cap=definitions_.at(c.definitionContentId).cargoCapacity;if(t.direction==DepotTransferDirection::IntoDepot&&cap-used(c)<t.count)return OrbitalServiceFailure::CapacityExceeded;if(t.direction==DepotTransferDirection::OutOfDepot){auto*s=stack(c,t.itemStableId);if(!s||s->contentId!=t.contentId||s->count<t.count)return OrbitalServiceFailure::MissingCargo;}t.state=ServiceTransactionState::Reserved;depotTransactions_[t.stableId]=t;return OrbitalServiceFailure::None;}
OrbitalServiceFailure OrbitalConstructRuntime::commitDepotTransfer(std::uint64_t id){auto t=depotTransactions_.find(id);if(t==depotTransactions_.end()||t->second.state!=ServiceTransactionState::Reserved)return OrbitalServiceFailure::InvalidRequest;auto&x=t->second;auto&i=constructs_.at(x.constructId);if(!operational(i,OrbitalCapability::CargoDepot))return i.powered?OrbitalServiceFailure::Inactive:OrbitalServiceFailure::Unpowered;if(x.direction==DepotTransferDirection::IntoDepot){if(insertCargo(i.stableId,{x.itemStableId,x.contentId,x.count})!=x.count)return OrbitalServiceFailure::CapacityExceeded;}else if(extractCargo(i.stableId,x.itemStableId,x.count)!=x.count)return OrbitalServiceFailure::MissingCargo;x.state=ServiceTransactionState::Committed;x.revision=elysium::safe::saturatingIncrement(x.revision);return OrbitalServiceFailure::None;}
bool OrbitalConstructRuntime::cancelDepotTransfer(std::uint64_t id){auto i=depotTransactions_.find(id);if(i==depotTransactions_.end()||i->second.state==ServiceTransactionState::Committed)return false;i->second.state=ServiceTransactionState::Cancelled;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}
OrbitalServiceFailure OrbitalConstructRuntime::beginDrydock(DrydockTransaction t){if(!t.stableId||!t.constructId||!t.shipStableId)return OrbitalServiceFailure::InvalidRequest;if(drydockTransactions_.contains(t.stableId))return OrbitalServiceFailure::DuplicateTransaction;auto i=constructs_.find(t.constructId);if(i==constructs_.end())return OrbitalServiceFailure::MissingConstruct;if(!operational(i->second,OrbitalCapability::Drydock))return i->second.powered?OrbitalServiceFailure::Inactive:OrbitalServiceFailure::Unpowered;if(t.operation==DrydockOperation::InstallModule&&!t.moduleItemStableId)return OrbitalServiceFailure::InvalidRequest;if(t.operation==DrydockOperation::RepairHull&&(!std::isfinite(t.requestedHullRepair)||t.requestedHullRepair<=0))return OrbitalServiceFailure::InvalidRequest;if(t.materialCount){auto*s=stack(i->second,t.materialContentId);(void)s;}t.state=ServiceTransactionState::Reserved;drydockTransactions_[t.stableId]=t;return OrbitalServiceFailure::None;}
OrbitalServiceFailure OrbitalConstructRuntime::commitDrydock(std::uint64_t id){auto i=drydockTransactions_.find(id);if(i==drydockTransactions_.end()||i->second.state!=ServiceTransactionState::Reserved)return OrbitalServiceFailure::InvalidRequest;auto&c=constructs_.at(i->second.constructId);if(!operational(c,OrbitalCapability::Drydock))return c.powered?OrbitalServiceFailure::Inactive:OrbitalServiceFailure::Unpowered;i->second.state=ServiceTransactionState::Committed;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return OrbitalServiceFailure::None;}
bool OrbitalConstructRuntime::cancelDrydock(std::uint64_t id){auto i=drydockTransactions_.find(id);if(i==drydockTransactions_.end()||i->second.state==ServiceTransactionState::Committed)return false;i->second.state=ServiceTransactionState::Cancelled;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}
std::uint64_t OrbitalConstructRuntime::insertCargo(std::uint64_t id,OrbitalCargoStack s){auto i=constructs_.find(id);if(i==constructs_.end()||!s.itemStableId||!s.contentId||!s.count)return 0;auto d=definitions_.find(i->second.definitionContentId);if(d==definitions_.end()||!(d->second.capabilities&orbitalCapability(OrbitalCapability::CargoDepot)))return 0;const auto room=d->second.cargoCapacity-used(i->second);const auto n=std::min(room,s.count);if(!n)return 0;s.count=n;i->second.cargo.push_back(s);normalize(i->second);i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return n;}
std::uint64_t OrbitalConstructRuntime::extractCargo(std::uint64_t id,std::uint64_t item,std::uint64_t count){auto i=constructs_.find(id);if(i==constructs_.end()||!count)return 0;auto*s=stack(i->second,item);if(!s)return 0;auto n=std::min(count,s->count);s->count-=n;if(!s->count)i->second.cargo.erase(std::remove_if(i->second.cargo.begin(),i->second.cargo.end(),[&](auto&x){return x.itemStableId==item;}),i->second.cargo.end());i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return n;}
OrbitalConstructSnapshot OrbitalConstructRuntime::snapshot()const{OrbitalConstructSnapshot s;for(auto&[_,x]:definitions_)s.definitions.push_back(x);for(auto&[_,x]:constructs_)s.constructs.push_back(x);for(auto&[_,x]:depotTransactions_)s.depotTransactions.push_back(x);for(auto&[_,x]:drydockTransactions_)s.drydockTransactions.push_back(x);return s;}
bool OrbitalConstructRuntime::restore(const OrbitalConstructSnapshot&s){OrbitalConstructRuntime r;for(auto x:s.definitions)if(!r.publish(x))return false;for(auto x:s.constructs)if(!r.create(x))return false;for(auto x:s.depotTransactions){if(!x.stableId||!r.constructs_.contains(x.constructId)||r.depotTransactions_.contains(x.stableId))return false;r.depotTransactions_[x.stableId]=x;}for(auto x:s.drydockTransactions){if(!x.stableId||!r.constructs_.contains(x.constructId)||r.drydockTransactions_.contains(x.stableId))return false;r.drydockTransactions_[x.stableId]=x;}*this=std::move(r);return true;}
} // namespace elysium::orbital
