#include "orbital/OrbitalCapabilityAdapters.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
namespace elysium::orbital{
bool OrbitalCapabilityAdapters::create(AdvancedOrbitalState s){if(!s.stableId||!s.parentConstructId||!s.systemId||states_.contains(s.stableId)||!std::isfinite(s.integrity)||!std::isfinite(s.exposureMultiplier))return false;s.integrity=elysium::safe::nonNegative(s.integrity,1.0);s.exposureMultiplier=elysium::safe::nonNegative(s.exposureMultiplier);if(s.kind!=AdvancedOrbitalKind::GateAnchor)s.gateActive=false;states_[s.stableId]=s;return true;}
bool OrbitalCapabilityAdapters::setPowered(std::uint64_t id,bool v){auto i=states_.find(id);if(i==states_.end())return false;i->second.powered=v;if(!v&&i->second.kind==AdvancedOrbitalKind::GateAnchor)i->second.gateActive=false;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}bool OrbitalCapabilityAdapters::setEnabled(std::uint64_t id,bool v){auto i=states_.find(id);if(i==states_.end())return false;i->second.enabled=v;if(!v&&i->second.kind==AdvancedOrbitalKind::GateAnchor)i->second.gateActive=false;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}bool OrbitalCapabilityAdapters::repair(std::uint64_t id,double amount){auto i=states_.find(id);if(i==states_.end()||!std::isfinite(amount)||amount<=0)return false;i->second.integrity=elysium::safe::finiteClamp(i->second.integrity+amount,0.0,1.0);i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}bool OrbitalCapabilityAdapters::setGateSatisfiedMask(std::uint64_t id,std::uint64_t mask){auto i=states_.find(id);if(i==states_.end()||i->second.kind!=AdvancedOrbitalKind::GateAnchor)return false;i->second.gateSatisfiedMask=mask;if((mask&i->second.gateRequiredMask)!=i->second.gateRequiredMask)i->second.gateActive=false;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}
std::uint64_t OrbitalCapabilityAdapters::insertResource(std::uint64_t id,ResourceQuantity q){if(!states_.contains(id)||!q.contentId||!q.count)return 0;auto&n=inventory_[id][q.contentId];n=elysium::safe::saturatingAdd(n,q.count);return q.count;}std::uint64_t OrbitalCapabilityAdapters::resourceCount(std::uint64_t id,std::uint64_t content)const{auto i=inventory_.find(id);if(i==inventory_.end())return 0;auto j=i->second.find(content);return j==i->second.end()?0:j->second;}
AdapterFailure OrbitalCapabilityAdapters::runRefineryBatch(const RefineryBatchRequest&r,StandingEmission*e){if(!r.transactionId||!r.constructId||!r.recipeContentId||r.outputs.empty())return AdapterFailure::InvalidRequest;if(processed_.contains(r.transactionId))return AdapterFailure::DuplicateTransaction;auto i=states_.find(r.constructId);if(i==states_.end())return AdapterFailure::MissingConstruct;auto&s=i->second;if(s.kind!=AdvancedOrbitalKind::Refinery)return AdapterFailure::WrongKind;if(!s.enabled)return AdapterFailure::Disabled;if(!s.powered)return AdapterFailure::Unpowered;if(s.integrity<=0)return AdapterFailure::Damaged;std::map<std::uint64_t,std::uint64_t>need;for(auto q:r.inputs){if(!q.contentId||!q.count)return AdapterFailure::InvalidRequest;need[q.contentId]=elysium::safe::saturatingAdd(need[q.contentId],q.count);}for(auto[q,n]:need)if(resourceCount(r.constructId,q)<n)return AdapterFailure::MissingInput;auto staged=inventory_[r.constructId];for(auto[q,n]:need)staged[q]-=n;for(auto q:r.outputs){if(!q.contentId||!q.count)return AdapterFailure::InvalidRequest;staged[q.contentId]=elysium::safe::saturatingAdd(staged[q.contentId],q.count);}inventory_[r.constructId]=std::move(staged);processed_[r.transactionId]=true;s.revision=elysium::safe::saturatingIncrement(s.revision);if(e)*e={s.stableId,s.systemId,r.recipeContentId,elysium::safe::nonNegative(r.standingSignal*s.exposureMultiplier)};return AdapterFailure::None;}
DefenseProjection OrbitalCapabilityAdapters::defense(std::uint64_t id)const{DefenseProjection o;auto i=states_.find(id);if(i==states_.end()||i->second.kind!=AdvancedOrbitalKind::DefensePlatform||!i->second.enabled||!i->second.powered||i->second.integrity<=0)return o;o.available=true;o.constructStableId=id;o.systemId=i->second.systemId;o.claimStableId=i->second.claimStableId;o.readiness=elysium::safe::finiteClamp(i->second.integrity,0.0,1.0);return o;}
AdapterFailure OrbitalCapabilityAdapters::activateGate(std::uint64_t id){auto i=states_.find(id);if(i==states_.end())return AdapterFailure::MissingConstruct;auto&s=i->second;if(s.kind!=AdvancedOrbitalKind::GateAnchor)return AdapterFailure::WrongKind;if(!s.enabled)return AdapterFailure::Disabled;if(!s.powered)return AdapterFailure::Unpowered;if(s.integrity<=0)return AdapterFailure::Damaged;if((s.gateSatisfiedMask&s.gateRequiredMask)!=s.gateRequiredMask)return AdapterFailure::PrerequisiteMissing;s.gateActive=true;s.revision=elysium::safe::saturatingIncrement(s.revision);return AdapterFailure::None;}bool OrbitalCapabilityAdapters::deactivateGate(std::uint64_t id){auto i=states_.find(id);if(i==states_.end()||i->second.kind!=AdvancedOrbitalKind::GateAnchor)return false;i->second.gateActive=false;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}GateProjection OrbitalCapabilityAdapters::gate(std::uint64_t id)const{GateProjection o;auto i=states_.find(id);if(i==states_.end()||i->second.kind!=AdvancedOrbitalKind::GateAnchor||!i->second.gateActive)return o;o.active=true;o.constructStableId=id;o.systemId=i->second.systemId;o.routeCapabilityKey=i->second.stableId;return o;}
const AdvancedOrbitalState*OrbitalCapabilityAdapters::find(std::uint64_t id)const{auto i=states_.find(id);return i==states_.end()?nullptr:&i->second;}AdvancedOrbitalSnapshot OrbitalCapabilityAdapters::snapshot()const{AdvancedOrbitalSnapshot s;for(auto&[_,x]:states_)s.states.push_back(x);for(auto&[id,m]:inventory_){std::vector<ResourceQuantity>v;for(auto&[c,n]:m)v.push_back({c,n});s.inventories.push_back({id,std::move(v)});}for(auto&[id,_]:processed_)s.processedTransactions.push_back(id);return s;}bool OrbitalCapabilityAdapters::restore(const AdvancedOrbitalSnapshot&s){OrbitalCapabilityAdapters r;for(auto x:s.states)if(!r.create(x))return false;for(auto&[id,v]:s.inventories){if(!r.states_.contains(id))return false;for(auto q:v)r.insertResource(id,q);}for(auto id:s.processedTransactions){if(!id||r.processed_.contains(id))return false;r.processed_[id]=true;}*this=std::move(r);return true;}
} // namespace elysium::orbital
