#include "rift/ExpeditionRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
namespace elysium::rift { namespace {
std::uint64_t mix(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);} 
std::uint64_t themed(std::uint64_t seed,std::uint64_t room,std::uint64_t domain,std::uint64_t theme){auto v=mix(seed^mix(room)^mix(domain)^mix(theme));return v?v:1;}
void mergeRewards(std::vector<ExpeditionReward>&dst,const std::vector<ExpeditionReward>&src){for(const auto&r:src){if(!r.contentId||!r.count)continue;auto it=std::find_if(dst.begin(),dst.end(),[&](const auto&x){return x.contentId==r.contentId;});if(it==dst.end())dst.push_back(r);else it->count=elysium::safe::saturatingAdd(it->count,r.count);}std::sort(dst.begin(),dst.end(),[](auto&a,auto&b){return a.contentId<b.contentId;});}
void expireRunBoons(std::vector<ExpeditionBoon>&b){b.erase(std::remove_if(b.begin(),b.end(),[](auto&x){return !x.permanent;}),b.end());}
}
bool ExpeditionRuntime::create(ExpeditionSession s){if(!s.stableId||!s.riftStableId||!s.systemStableId||sessions_.contains(s.stableId))return false;s.heat=elysium::safe::nonNegative(s.heat);std::sort(s.banked.begin(),s.banked.end(),[](auto&a,auto&b){return a.contentId<b.contentId;});std::sort(s.unbanked.begin(),s.unbanked.end(),[](auto&a,auto&b){return a.contentId<b.contentId;});sessions_.emplace(s.stableId,std::move(s));return true;}
const ExpeditionSession*ExpeditionRuntime::find(std::uint64_t id)const{auto i=sessions_.find(id);return i==sessions_.end()?nullptr:&i->second;}
ExpeditionResult ExpeditionRuntime::commit(const ExpeditionTransaction&t,const HeatPromotionPolicy&policy){if(auto p=processed_.find(t.stableId);p!=processed_.end()){auto r=p->second;r.duplicate=true;return r;}ExpeditionResult out;if(!t.stableId||!t.sessionStableId){out.failure=ExpeditionFailure::InvalidTransaction;return out;}auto i=sessions_.find(t.sessionStableId);if(i==sessions_.end()){out.failure=ExpeditionFailure::InvalidSession;return out;}auto&s=i->second;if(s.state!=ExpeditionState::Active){out.failure=ExpeditionFailure::WrongState;return out;}if(t.expectedRevision!=s.revision){out.failure=ExpeditionFailure::RevisionConflict;return out;}const double oldHeat=s.heat;switch(t.kind){case ExpeditionTxnKind::PushDeeper:s.currentDepth=elysium::safe::saturatingAdd(s.currentDepth,t.depthDelta);mergeRewards(s.unbanked,t.rewardDelta);for(auto b:t.boonDelta)if(b.contentId){b.acquiredDepth=s.currentDepth;s.boons.push_back(b);}s.heat=elysium::safe::nonNegative(s.heat+elysium::safe::nonNegative(t.heatDelta));break;case ExpeditionTxnKind::BankExtract:mergeRewards(s.unbanked,t.rewardDelta);mergeRewards(s.banked,s.unbanked);s.unbanked.clear();expireRunBoons(s.boons);s.state=ExpeditionState::Extracted;s.heat=elysium::safe::nonNegative(s.heat+elysium::safe::nonNegative(t.heatDelta));break;case ExpeditionTxnKind::FailRun:s.unbanked.clear();expireRunBoons(s.boons);s.state=ExpeditionState::Failed;s.heat=elysium::safe::nonNegative(s.heat+elysium::safe::nonNegative(t.heatDelta));break;}s.revision=elysium::safe::saturatingIncrement(s.revision);out.committed=true;out.revision=s.revision;const double threshold=elysium::safe::nonNegative(policy.threshold);if(threshold>0.0&&oldHeat<threshold&&s.heat>=threshold)out.standingIntents.push_back({s.stableId,s.systemStableId,s.heat});processed_[t.stableId]=out;return out;}
std::vector<RiftRoomTheme>ExpeditionRuntime::theme(const RiftTopology&t,RiftPlanetTheme pt,std::uint64_t universeSeed)const{std::vector<RiftRoomTheme>o;o.reserve(t.rooms.size());const auto themeId=static_cast<std::uint64_t>(pt)+1;for(const auto&r:t.rooms)o.push_back({r.stableRoomId,themed(universeSeed,r.stableRoomId,1,themeId),themed(universeSeed,r.stableRoomId,2,themeId),themed(universeSeed,r.stableRoomId,3,themeId),pt==RiftPlanetTheme::Anomalous});std::sort(o.begin(),o.end(),[](auto&a,auto&b){return a.roomStableId<b.roomStableId;});return o;}
ExpeditionSnapshot ExpeditionRuntime::snapshot()const{ExpeditionSnapshot o;for(auto&[_,s]:sessions_)o.sessions.push_back(s);for(auto&[id,_]:processed_)o.processedTransactionIds.push_back(id);return o;}
bool ExpeditionRuntime::restore(const ExpeditionSnapshot&snap){ExpeditionRuntime r;for(auto s:snap.sessions)if(!r.create(std::move(s)))return false;for(auto id:snap.processedTransactionIds){if(!id||r.processed_.contains(id))return false;ExpeditionResult x;x.committed=true;x.duplicate=true;r.processed_[id]=x;}*this=std::move(r);return true;}
} // namespace elysium::rift
