#include "rift/RiftTopology.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <map>
#include <queue>
#include <set>
namespace elysium::rift{namespace{std::uint64_t mix(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}std::uint64_t h(std::uint64_t a,std::uint64_t b,std::uint64_t c){auto x=mix(a^0x524946545f544f50ULL);x=mix(x^(mix(b+0x100000001b3ULL)));x=mix(x^(mix(c+0x9e3779b97f4a7c15ULL)));return x;}std::uint64_t roomId(std::uint64_t r,RiftCoord c){auto v=h(r,static_cast<std::uint64_t>(c.x),static_cast<std::uint64_t>(c.y));return v?v:1;}int key(RiftCoord c){return int(c.y)*9+int(c.x);}std::array<RiftCoord,4> neighbors(RiftCoord c){return {{{static_cast<std::uint8_t>(c.x+1),c.y},{static_cast<std::uint8_t>(c.x-1),c.y},{c.x,static_cast<std::uint8_t>(c.y+1)},{c.x,static_cast<std::uint8_t>(c.y-1)}}};}bool in(RiftCoord c){return c.x<9&&c.y<9;}double unit(std::uint64_t x){return double(x>>11)*(1.0/9007199254740992.0);}}
RiftTopology RiftTopologyGenerator::generate(std::uint64_t rid,std::uint64_t seed,const RiftTopologyConfig&cfg,std::uint32_t workers)const{(void)workers;RiftTopology o;if(!rid||!seed||cfg.targetRooms==0||!std::isfinite(cfg.newestCellBias)||!std::isfinite(cfg.lootDepthFraction))return o;const auto target=std::min<std::uint32_t>(81,cfg.targetRooms);std::vector<RiftCoord> cells{{4,4}};std::set<int> used{key({4,4})};std::vector<std::pair<RiftCoord,RiftCoord>>edges;std::uint64_t step=0;while(cells.size()<target){std::vector<std::size_t>parents;for(std::size_t i=0;i<cells.size();++i){for(auto n:neighbors(cells[i]))if(in(n)&&!used.contains(key(n))){parents.push_back(i);break;}}if(parents.empty())break;const auto hv=h(seed,rid,step++);std::size_t pi=0;if(unit(hv)<std::clamp(cfg.newestCellBias,0.0,1.0))pi=parents.back();else pi=parents[static_cast<std::size_t>((hv>>17)%parents.size())];auto opts=neighbors(cells[pi]);std::vector<RiftCoord>avail;for(auto n:opts)if(in(n)&&!used.contains(key(n)))avail.push_back(n);std::sort(avail.begin(),avail.end(),[](auto a,auto b){return key(a)<key(b);});if(avail.empty())continue;auto n=avail[static_cast<std::size_t>((hv>>33)%avail.size())];used.insert(key(n));edges.push_back({cells[pi],n});cells.push_back(n);}std::map<int,std::uint32_t>depth;std::map<int,std::vector<int>>adj;for(auto[a,b]:edges){adj[key(a)].push_back(key(b));adj[key(b)].push_back(key(a));}std::queue<int>q;depth[key({4,4})]=0;q.push(key({4,4}));while(!q.empty()){auto k=q.front();q.pop();for(auto n:adj[k])if(!depth.contains(n)){depth[n]=depth[k]+1;q.push(n);}}std::uint32_t maxd=0;for(auto&[_,d]:depth)maxd=std::max(maxd,d);std::uint64_t boss=0;for(auto c:cells)if(depth[key(c)]==maxd){auto id=roomId(rid,c);if(!boss||id<boss)boss=id;}const auto lootThreshold=static_cast<std::uint32_t>(std::floor(double(maxd)*std::clamp(cfg.lootDepthFraction,0.0,1.0)));for(auto c:cells){auto id=roomId(rid,c);const bool dead=adj[key(c)].size()==1&&key(c)!=key({4,4});o.rooms.push_back({id,c,depth[key(c)],key(c)==key({4,4}),id==boss,dead&&depth[key(c)]>=lootThreshold});}std::sort(o.rooms.begin(),o.rooms.end(),[](auto&a,auto&b){return a.stableRoomId<b.stableRoomId;});for(auto[a,b]:edges){auto x=roomId(rid,a),y=roomId(rid,b);if(x>y)std::swap(x,y);o.doors.push_back({x,y});}std::sort(o.doors.begin(),o.doors.end(),[](auto&a,auto&b){return a.roomA<b.roomA||(a.roomA==b.roomA&&a.roomB<b.roomB);});o.riftStableId=rid;o.seed=seed;return o;}
bool RiftTopologyGenerator::validate(const RiftTopology&t)const{if(!t.riftStableId||t.rooms.empty())return false;std::set<std::uint64_t>ids;std::map<std::uint64_t,std::vector<std::uint64_t>>adj;std::uint64_t entrance=0,boss=0;std::uint32_t maxd=0;for(auto&r:t.rooms){if(!r.stableRoomId||r.coord.x>=9||r.coord.y>=9||!ids.insert(r.stableRoomId).second)return false;if(r.entrance){if(entrance||r.coord!=RiftCoord{4,4}||r.depth!=0)return false;entrance=r.stableRoomId;}if(r.boss){if(boss)return false;boss=r.stableRoomId;}maxd=std::max(maxd,r.depth);}if(!entrance||!boss)return false;for(auto&d:t.doors){if(!ids.contains(d.roomA)||!ids.contains(d.roomB)||d.roomA>=d.roomB)return false;adj[d.roomA].push_back(d.roomB);adj[d.roomB].push_back(d.roomA);}std::set<std::uint64_t>seen;std::queue<std::uint64_t>q;q.push(entrance);seen.insert(entrance);while(!q.empty()){auto x=q.front();q.pop();for(auto n:adj[x])if(seen.insert(n).second)q.push(n);}if(seen.size()!=t.rooms.size())return false;for(auto&r:t.rooms)if(r.boss&&r.depth!=maxd)return false;return true;}
} // namespace elysium::rift
