#include "save/AtomicSaveGeneration.hpp"
#include <algorithm>
#include <cstring>
namespace elysium::save {namespace{template<class T>void put(std::vector<std::uint8_t>&o,T v){for(std::size_t i=0;i<sizeof(T);++i)o.push_back(static_cast<std::uint8_t>((static_cast<std::uint64_t>(v)>>(8*i))&0xff));}template<class T>bool get(const std::vector<std::uint8_t>&b,std::size_t&p,T&v){if(p+sizeof(T)>b.size())return false;std::uint64_t x=0;for(std::size_t i=0;i<sizeof(T);++i)x|=std::uint64_t(b[p++])<<(8*i);v=static_cast<T>(x);return true;}}
std::uint64_t AtomicSaveGeneration::checksum(const std::vector<std::uint8_t>&b){std::uint64_t h=1469598103934665603ULL;for(auto v:b){h^=v;h*=1099511628211ULL;}return h?h:1;}
std::vector<std::uint8_t>AtomicSaveGeneration::pack(const SaveGeneration&g)const{std::vector<std::uint8_t>o;put(o,g.meta.generationId);put(o,g.meta.previousGenerationId);put(o,g.meta.generatorFingerprint);put(o,g.meta.formatVersion);put(o,g.meta.spatialSchemaVersion);put<std::uint64_t>(o,g.payload.size());o.insert(o.end(),g.payload.begin(),g.payload.end());put(o,checksum(o));return o;}
SavePublishFailure AtomicSaveGeneration::unpack(const std::vector<std::uint8_t>&b,SaveGeneration&o)const{if(b.size()<sizeof(std::uint64_t))return SavePublishFailure::Invalid;std::size_t p=0;SaveGeneration g;std::uint64_t n{};if(!get(b,p,g.meta.generationId)||!get(b,p,g.meta.previousGenerationId)||!get(b,p,g.meta.generatorFingerprint)||!get(b,p,g.meta.formatVersion)||!get(b,p,g.meta.spatialSchemaVersion)||!get(b,p,n)||n>b.size()-p-sizeof(std::uint64_t))return SavePublishFailure::Invalid;g.payload.assign(b.begin()+static_cast<std::ptrdiff_t>(p),b.begin()+static_cast<std::ptrdiff_t>(p+n));p+=n;std::uint64_t stored{};if(!get(b,p,stored)||p!=b.size())return SavePublishFailure::Invalid;std::vector<std::uint8_t>prefix(b.begin(),b.end()-static_cast<std::ptrdiff_t>(sizeof(std::uint64_t)));if(checksum(prefix)!=stored)return SavePublishFailure::ChecksumMismatch;g.meta.checksum=stored;o=std::move(g);return SavePublishFailure::None;}
SavePublishFailure AtomicSaveGeneration::publish(IAtomicSaveStore&s,SaveGeneration g){if(!g.meta.generationId||!g.meta.generatorFingerprint)return SavePublishFailure::Invalid;g.meta.previousGenerationId=s.manifest();auto bytes=pack(g);if(!s.writeTemp(g.meta.generationId,bytes))return SavePublishFailure::WriteFailed;if(!s.flushTemp(g.meta.generationId))return SavePublishFailure::FlushFailed;if(!s.publishTemp(g.meta.generationId))return SavePublishFailure::PublishFailed;if(!s.setManifest(g.meta.generationId))return SavePublishFailure::ManifestFailed;return SavePublishFailure::None;}
SavePublishFailure AtomicSaveGeneration::recover(const IAtomicSaveStore&s,SaveGeneration&o)const{auto id=s.manifest();std::vector<std::uint8_t>b;while(id){if(s.readPublished(id,b)){SaveGeneration g;auto r=unpack(b,g);if(r==SavePublishFailure::None){o=std::move(g);return r;}if(r!=SavePublishFailure::ChecksumMismatch)return r;} // if manifest generation is corrupt, try previous id encoded only if parseable prefix
std::size_t p=0;std::uint64_t cur{},prev{};if(b.size()>=16&&get(b,p,cur)&&get(b,p,prev)&&prev!=id){id=prev;b.clear();}else break;}return SavePublishFailure::NoGoodGeneration;}
SpatialDeltaBatch AtomicSaveGeneration::compact(const SpatialDeltaBatch&b)const{struct K{SpatialAddress a;SpatialDeltaKind k{};std::uint64_t o{};auto operator<=>(const K&)const=default;};std::map<K,SpatialDelta>m;for(auto&d:b.deltas){K k{d.address,d.kind,d.stableObjectId};auto i=m.find(k);if(i==m.end()||d.revision>=i->second.revision)m[k]=d;}SpatialDeltaBatch o;o.schemaVersion=b.schemaVersion;for(auto&[_,d]:m)o.deltas.push_back(d);return o;}
} // namespace elysium::save
