// Intended function: plan two-generation atomic save publication so partially written multi-file saves never become the active manifest.
#include "save/SaveGenerationManifest.hpp"
#include <algorithm>
#include <sstream>
#include <unordered_set>
namespace elysium{
bool validateSaveManifest(const SaveGenerationManifest&m,std::string*e){if(m.schema!=1){if(e)*e="unsupported schema";return false;}if(!m.worldId||!m.activeGeneration){if(e)*e="missing world/generation";return false;}std::unordered_set<std::string>names;for(auto&f:m.files){if(f.logicalName.empty()||f.path.empty()||!f.generation||!names.insert(f.logicalName).second){if(e)*e="invalid/duplicate file";return false;}if(f.required&&!f.checksum){if(e)*e="required file missing checksum";return false;}}return true;}
std::string serializeSaveManifest(const SaveGenerationManifest&m){std::ostringstream o;o<<"ELYSIUM_SAVE_MANIFEST "<<m.schema<<' '<<m.worldId<<' '<<m.activeGeneration<<' '<<m.previousGeneration<<'\n';for(auto&f:m.files)o<<f.logicalName<<'\t'<<f.path<<'\t'<<f.generation<<'\t'<<f.checksum<<'\t'<<f.bytes<<'\t'<<(f.required?1:0)<<'\n';return o.str();}
std::optional<SaveGenerationManifest> parseSaveManifest(const std::string&t,std::string*e){std::istringstream in(t);std::string magic;SaveGenerationManifest m;if(!(in>>magic>>m.schema>>m.worldId>>m.activeGeneration>>m.previousGeneration)||magic!="ELYSIUM_SAVE_MANIFEST"){if(e)*e="bad header";return std::nullopt;}std::string line;std::getline(in,line);while(std::getline(in,line)){if(line.empty())continue;std::istringstream r(line);SaveFileRecord f;int req{};if(!std::getline(r,f.logicalName,'\t')||!std::getline(r,f.path,'\t')||!(r>>f.generation)){if(e)*e="bad record";return std::nullopt;}r.ignore(1);if(!(r>>f.checksum)){if(e)*e="bad checksum";return std::nullopt;}r.ignore(1);if(!(r>>f.bytes)){if(e)*e="bad size";return std::nullopt;}r.ignore(1);if(!(r>>req)){if(e)*e="bad required";return std::nullopt;}f.required=req!=0;m.files.push_back(std::move(f));}if(!validateSaveManifest(m,e))return std::nullopt;return m;}
SavePublicationPlan planSavePublication(const SaveGenerationManifest&c,std::vector<SaveFileRecord>s){SavePublicationPlan p;p.next.schema=1;p.next.worldId=c.worldId;p.next.previousGeneration=c.activeGeneration;p.next.activeGeneration=c.activeGeneration+1;for(auto&f:s){f.generation=p.next.activeGeneration;std::string tmp=f.path+".tmp."+std::to_string(p.next.activeGeneration);p.atomicRenames.push_back({tmp,f.path});p.next.files.push_back(f);}for(auto&f:c.files)if(f.generation+1<p.next.activeGeneration)p.pruneAfterPublish.push_back(f.path);std::sort(p.next.files.begin(),p.next.files.end(),[](auto&a,auto&b){return a.logicalName<b.logicalName;});return p;}
}
