#include "save/SpatialDeltaCodec.hpp"
#include <algorithm>
#include <cstring>
#include <limits>
namespace elysium::save {namespace{template<class T>void put(std::vector<std::uint8_t>&o,T v){static_assert(std::is_integral_v<T>);using U=std::make_unsigned_t<T>;U x=static_cast<U>(v);for(std::size_t i=0;i<sizeof(T);++i)o.push_back(static_cast<std::uint8_t>((x>>(8*i))&0xff));}template<class T>bool get(const std::vector<std::uint8_t>&b,std::size_t&p,T&v){if(p+sizeof(T)>b.size())return false;using U=std::make_unsigned_t<T>;U x=0;for(std::size_t i=0;i<sizeof(T);++i)x|=static_cast<U>(b[p++])<<(8*i);v=static_cast<T>(x);return true;}}
DeltaCodecFailure SpatialDeltaCodec::validate(const SpatialDelta&d)const{if(!d.address.worldStableId||!d.revision)return DeltaCodecFailure::InvalidAddress;if((d.kind==SpatialDeltaKind::ObjectState||d.kind==SpatialDeltaKind::GeneratedTombstone||d.kind==SpatialDeltaKind::PlacedMarker)&&!d.stableObjectId)return DeltaCodecFailure::InvalidDelta;return DeltaCodecFailure::None;}
std::vector<std::uint8_t>SpatialDeltaCodec::encode(const SpatialDeltaBatch&b)const{std::vector<std::uint8_t>o;if(b.schemaVersion!=1)return o;put(o,b.schemaVersion);put<std::uint64_t>(o,b.deltas.size());for(auto&d:b.deltas){if(validate(d)!=DeltaCodecFailure::None)return {};put(o,static_cast<std::uint8_t>(d.address.domain));put(o,d.address.worldStableId);put(o,d.address.spaceStableId);put(o,d.address.x);put(o,d.address.y);put(o,d.address.z);put(o,d.address.subdomain);put(o,static_cast<std::uint8_t>(d.kind));put(o,d.stableObjectId);put(o,d.contentId);put(o,d.revision);put<std::uint64_t>(o,d.payload.size());o.insert(o.end(),d.payload.begin(),d.payload.end());}return o;}
DeltaCodecFailure SpatialDeltaCodec::decode(const std::vector<std::uint8_t>&b,SpatialDeltaBatch&o)const{std::size_t p=0;SpatialDeltaBatch x;if(!get(b,p,x.schemaVersion))return DeltaCodecFailure::Malformed;if(x.schemaVersion!=1)return DeltaCodecFailure::UnsupportedVersion;std::uint64_t n{};if(!get(b,p,n)||n>b.size())return DeltaCodecFailure::Malformed;for(std::uint64_t i=0;i<n;++i){SpatialDelta d;std::uint8_t dom{},kind{};std::uint64_t bytes{};if(!get(b,p,dom)||!get(b,p,d.address.worldStableId)||!get(b,p,d.address.spaceStableId)||!get(b,p,d.address.x)||!get(b,p,d.address.y)||!get(b,p,d.address.z)||!get(b,p,d.address.subdomain)||!get(b,p,kind)||!get(b,p,d.stableObjectId)||!get(b,p,d.contentId)||!get(b,p,d.revision)||!get(b,p,bytes)||bytes>b.size()-p)return DeltaCodecFailure::Malformed;if(dom>static_cast<std::uint8_t>(SpatialDomain::RiftCell)||kind>static_cast<std::uint8_t>(SpatialDeltaKind::EnvironmentalLocal))return DeltaCodecFailure::Malformed;d.address.domain=static_cast<SpatialDomain>(dom);d.kind=static_cast<SpatialDeltaKind>(kind);d.payload.assign(b.begin()+static_cast<std::ptrdiff_t>(p),b.begin()+static_cast<std::ptrdiff_t>(p+bytes));p+=bytes;if(validate(d)!=DeltaCodecFailure::None)return DeltaCodecFailure::InvalidDelta;x.deltas.push_back(std::move(d));}if(p!=b.size())return DeltaCodecFailure::Malformed;o=std::move(x);return DeltaCodecFailure::None;}
DeltaCodecFailure SpatialDeltaStore::apply(SpatialDelta d){SpatialDeltaCodec c;auto v=c.validate(d);if(v!=DeltaCodecFailure::None)return v;Key k{d.address,d.kind,d.stableObjectId};auto i=rows_.find(k);if(i==rows_.end()||d.revision>=i->second.revision)rows_[k]=std::move(d);return DeltaCodecFailure::None;}std::vector<SpatialDelta>SpatialDeltaStore::forAddress(const SpatialAddress&a)const{std::vector<SpatialDelta>o;for(auto&[k,d]:rows_)if(k.address==a)o.push_back(d);return o;}
} // namespace elysium::save
