#include "economy/SystemEconomyRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
namespace elysium::economy {namespace{std::uint64_t toU64(double v){if(!std::isfinite(v)||v<=0)return 0;const auto hi=static_cast<long double>(std::numeric_limits<std::uint64_t>::max());return static_cast<std::uint64_t>(std::min<long double>(v,hi));}}
bool SystemEconomyRuntime::publish(EconomyClassDef d){if(!std::isfinite(d.buyWeight)||!std::isfinite(d.sellWeight)||d.buyWeight<0||d.sellWeight<0)return false;classes_[d.type]=d;return true;}bool SystemEconomyRuntime::publish(CommodityDef d){if(!d.contentId||!d.baseValue)return false;commodities_[d.contentId]=d;return true;}bool SystemEconomyRuntime::createMarket(MarketState m){if(!m.stableId||!m.settlementStableId||!classes_.contains(m.economyClass)||markets_.contains(m.stableId))return false;for(auto&s:m.stock){if(!commodities_.contains(s.commodityId)||s.units>s.capacity)return false;}std::sort(m.stock.begin(),m.stock.end(),[](auto&a,auto&b){return a.commodityId<b.commodityId;});markets_[m.stableId]=std::move(m);return true;}
PriceBreakdown SystemEconomyRuntime::price(std::uint64_t mid,const PriceContext&c)const{PriceBreakdown o;auto mi=markets_.find(mid);auto ci=commodities_.find(c.commodityId);if(mi==markets_.end()||ci==commodities_.end())return o;auto cd=classes_.find(mi->second.economyClass);if(cd==classes_.end())return o;o.baseValue=ci->second.baseValue;o.classWeight=c.side==TradeSide::BuyFromMarket?cd->second.buyWeight:cd->second.sellWeight;auto si=std::find_if(mi->second.stock.begin(),mi->second.stock.end(),[&](auto&s){return s.commodityId==c.commodityId;});if(si!=mi->second.stock.end()&&si->capacity){const double fill=double(si->units)/double(si->capacity);o.stockPressure=c.side==TradeSide::BuyFromMarket?(1.5-0.75*fill):(0.5+0.75*(1.0-fill));}o.stockPressure=elysium::safe::nonNegative(o.stockPressure);o.standingModifier=elysium::safe::nonNegative(c.standingModifier);o.registrationModifier=elysium::safe::nonNegative(c.registrationModifier);o.finalUnitPrice=std::max<std::uint64_t>(1,toU64(double(o.baseValue)*o.classWeight*o.stockPressure*o.standingModifier*o.registrationModifier));return o;}
MarketTradeResult SystemEconomyRuntime::trade(const MarketTransaction&t,const PriceContext&pc){if(auto p=processed_.find(t.stableId);p!=processed_.end()){auto r=p->second;r.duplicate=true;return r;}MarketTradeResult o;if(!t.stableId||!t.marketStableId||!t.commodityId||!t.units){o.failure=MarketFailure::Invalid;return o;}auto mi=markets_.find(t.marketStableId);auto ci=commodities_.find(t.commodityId);if(mi==markets_.end()||ci==commodities_.end()){o.failure=MarketFailure::UnknownItem;return o;}if(t.progressionLevel<ci->second.progressionGate){o.failure=MarketFailure::ProgressionLocked;return o;}auto& m=mi->second;if(t.expectedMarketRevision!=m.revision){o.failure=MarketFailure::Invalid;return o;}auto si=std::find_if(m.stock.begin(),m.stock.end(),[&](auto&s){return s.commodityId==t.commodityId;});if(si==m.stock.end()){o.failure=MarketFailure::UnknownItem;return o;}if(t.side==TradeSide::BuyFromMarket){if(si->units<t.units){o.failure=MarketFailure::InsufficientStock;return o;}si->units-=t.units;}else{const auto room=si->capacity>si->units?si->capacity-si->units:0;const auto accepted=std::min(room,t.units);if(!accepted){o.failure=MarketFailure::InsufficientStock;return o;}si->units=elysium::safe::saturatingAdd(si->units,accepted);o.units=accepted;}if(!o.units)o.units=t.units;o.price=price(t.marketStableId,pc);o.totalValue=elysium::safe::saturatingMultiply(o.units,o.price.finalUnitPrice);m.revision=elysium::safe::saturatingIncrement(m.revision);o.revision=m.revision;o.imperialFileExposure=m.economyClass==EconomyClass::Imperial;o.committed=true;processed_[t.stableId]=o;return o;}
bool SystemEconomyRuntime::restock(std::uint64_t id,std::uint64_t epoch){auto i=markets_.find(id);if(i==markets_.end()||epoch<=i->second.restockEpoch)return false;auto delta=epoch-i->second.restockEpoch;for(auto&s:i->second.stock){const auto add=elysium::safe::saturatingMultiply(delta,s.restockPerEpoch);s.units=std::min(s.capacity,elysium::safe::saturatingAdd(s.units,add));}i->second.restockEpoch=epoch;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}const MarketState*SystemEconomyRuntime::market(std::uint64_t id)const{auto i=markets_.find(id);return i==markets_.end()?nullptr:&i->second;}
} // namespace elysium::economy
