#include "world/RoadInfrastructure.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>

namespace elysium::world {
namespace {
bool validSegment(const RoadSegment& s){return s.stableId&&s.worldId&&s.fromKey&&s.toKey&&s.fromKey!=s.toKey&&std::isfinite(s.widthMeters)&&s.widthMeters>=0&&std::isfinite(s.maximumLoad)&&s.maximumLoad>=0&&std::isfinite(s.speedMultiplier)&&s.speedMultiplier>=0&&std::isfinite(s.reliabilityBonus)&&s.reliabilityBonus>=0;}
bool sameEdge(const RoadSegment&s,const TerrainEdgeSample&e){return s.enabled&&s.worldId==e.worldId&&((s.fromKey==e.fromKey&&s.toKey==e.toKey)||(s.fromKey==e.toKey&&s.toKey==e.fromKey));}
}
InfrastructureEditResult RoadInfrastructure::upsert(RoadSegment s){InfrastructureEditResult r;if(!validSegment(s))return r;auto it=segments_.find(s.stableId);if(it!=segments_.end()&&it->second.regionKey!=s.regionKey)r.invalidatedRegionKeys.push_back(it->second.regionKey);segments_[s.stableId]=s;r.invalidatedRegionKeys.push_back(s.regionKey);std::sort(r.invalidatedRegionKeys.begin(),r.invalidatedRegionKeys.end());r.invalidatedRegionKeys.erase(std::unique(r.invalidatedRegionKeys.begin(),r.invalidatedRegionKeys.end()),r.invalidatedRegionKeys.end());r.changed=true;return r;}
InfrastructureEditResult RoadInfrastructure::erase(std::uint64_t id){InfrastructureEditResult r;auto it=segments_.find(id);if(it==segments_.end())return r;r.changed=true;r.invalidatedRegionKeys.push_back(it->second.regionKey);segments_.erase(it);return r;}
RoadCostResult RoadInfrastructure::evaluate(const TerrainEdgeSample&e,const VehicleTraversalProfile&v)const{RoadCostResult o;if(!e.worldId||!e.fromKey||!e.toKey||e.fromKey==e.toKey||!std::isfinite(e.baseCost)||e.baseCost<0||!std::isfinite(v.widthMeters)||v.widthMeters<0||!std::isfinite(v.mass)||v.mass<0){o.reason=RoadRouteReason::InvalidInput;o.explanation="invalid edge or vehicle profile";return o;}const auto slope=elysium::safe::nonNegative(e.slopeDegrees,90.0);const auto rough=elysium::safe::nonNegative(e.roughness);const auto gap=elysium::safe::nonNegative(e.gapMeters);const auto water=elysium::safe::nonNegative(e.waterDepthMeters);
const RoadSegment*best=nullptr;bool sawWidthBlock=false,sawLoadBlock=false,sawBridgeNeed=false;for(const auto&[_,s]:segments_)if(sameEdge(s,e)){if(v.widthMeters>s.widthMeters){sawWidthBlock=true;continue;}if(v.mass>s.maximumLoad){sawLoadBlock=true;continue;}if(gap>0&&s.kind!=InfrastructureKind::Bridge&&s.kind!=InfrastructureKind::Causeway&&!v.hover){sawBridgeNeed=true;continue;}if(!best||s.speedMultiplier>best->speedMultiplier||(s.speedMultiplier==best->speedMultiplier&&s.stableId<best->stableId))best=&s;}
if(best){o.traversable=true;o.infrastructureStableId=best->stableId;o.speedMultiplier=elysium::safe::nonNegative(best->speedMultiplier);o.reliability=elysium::safe::nonNegative(1.0+best->reliabilityBonus);o.cost=elysium::safe::nonNegative(e.baseCost/std::max(0.001,o.speedMultiplier));o.explanation="infrastructure bonus applied";return o;}
if(sawBridgeNeed){o.reason=RoadRouteReason::BridgeRequired;o.explanation="gap requires bridge/causeway capability";return o;}if(sawWidthBlock){o.reason=RoadRouteReason::WidthBlocked;o.explanation="infrastructure clearance is too narrow";return o;}if(sawLoadBlock){o.reason=RoadRouteReason::LoadBlocked;o.explanation="vehicle exceeds infrastructure load rating";return o;}
if(gap>0&&!v.hover){o.reason=RoadRouteReason::BridgeRequired;o.explanation="unbridged gap";return o;}if(!v.hover&&slope>v.maximumSlopeDegrees){o.reason=RoadRouteReason::SlopeBlocked;o.explanation="terrain slope exceeds vehicle profile";return o;}if(!v.hover&&rough>1.0){o.reason=RoadRouteReason::TerrainBlocked;o.explanation="terrain roughness exceeds unroaded traversal";return o;}if(water>0&&!v.canFord&&!v.hover){o.reason=RoadRouteReason::TerrainBlocked;o.explanation="water requires ford/hover or infrastructure";return o;}o.traversable=true;o.cost=elysium::safe::nonNegative(e.baseCost*(1.0+rough*0.5+slope/180.0));o.speedMultiplier=1.0;o.reliability=std::clamp(1.0-rough*0.25,0.0,1.0);o.explanation="unroaded route remains traversable";return o;}
std::vector<RoadSegment> RoadInfrastructure::snapshot()const{std::vector<RoadSegment>v;v.reserve(segments_.size());for(const auto&[_,s]:segments_)v.push_back(s);return v;}
bool RoadInfrastructure::restore(const std::vector<RoadSegment>&v){RoadInfrastructure staged;for(const auto&s:v)if(!staged.upsert(s).changed)return false;*this=std::move(staged);return true;}
} // namespace elysium::world
