#include "jobs/PriorityJobScheduler.hpp"
#include <algorithm>
#include <future>
namespace elysium::jobs {
WorkPriority PriorityJobScheduler::canonicalPriority(WorkClass c){switch(c){case WorkClass::EditRemesh:return WorkPriority::Critical;case WorkClass::VisibleGeneration:case WorkClass::VisibleMesh:return WorkPriority::High;case WorkClass::Prefetch:case WorkClass::Lod:case WorkClass::AiThink:case WorkClass::AiPerception:case WorkClass::PoiPrep:return WorkPriority::Medium;default:return WorkPriority::Low;}}
bool PriorityJobScheduler::setCurrentVersion(std::uint64_t d,std::uint64_t v){if(!d)return false;std::lock_guard l(mutex_);versions_[d]=v;return true;}
bool PriorityJobScheduler::stale(const ScheduledJob&j)const{if(!j.token.domainStableId)return false;auto i=versions_.find(j.token.domainStableId);return i!=versions_.end()&&i->second!=j.token.version;}
bool PriorityJobScheduler::shed(WorkClass c)const{return c==WorkClass::Prefetch||c==WorkClass::Validation||c==WorkClass::Telemetry||c==WorkClass::Compaction;}
JobDisposition PriorityJobScheduler::enqueue(ScheduledJob j,std::function<bool()> c,std::function<void()> p){if(!j.stableId||!c)return JobDisposition::Failed;std::lock_guard l(mutex_);if(j.token.domainStableId){auto vi=versions_.find(j.token.domainStableId);if(vi!=versions_.end()&&vi->second!=j.token.version){++stats_.cancelled;return JobDisposition::Cancelled;}}if(queue_.size()>=policy_.hardQueueLimit||(queue_.size()>=policy_.softQueueLimit&&shed(j.workClass))){++stats_.dropped;return JobDisposition::Dropped;}j.priority=canonicalPriority(j.workClass);j.sequence=nextSequence_++;queue_.push_back({j,std::move(c),std::move(p)});++stats_.queued;return JobDisposition::Queued;}
bool PriorityJobScheduler::pumpOne(elysium::JobSystem&pool){Entry e;{std::lock_guard l(mutex_);if(queue_.empty())return false;std::stable_sort(queue_.begin(),queue_.end(),[](auto&a,auto&b){if(a.job.priority!=b.job.priority)return a.job.priority<b.job.priority;return a.job.sequence<b.job.sequence;});e=std::move(queue_.front());queue_.erase(queue_.begin());if(stale(e.job)){++stats_.cancelled;return true;}}auto f=pool.submit([c=e.compute](){return c();});bool ok=false;try{ok=f.get();}catch(...){std::lock_guard l(mutex_);++stats_.failed;return true;}std::lock_guard l(mutex_);++stats_.computed;if(stale(e.job)){++stats_.cancelled;return true;}if(!ok){++stats_.failed;return true;}if(e.job.publicationRequired&&e.publish){e.publish();++stats_.published;}return true;}
void PriorityJobScheduler::drain(elysium::JobSystem&p){while(pumpOne(p)){}p.drain();}SchedulerStats PriorityJobScheduler::stats()const{std::lock_guard l(mutex_);return stats_;}std::size_t PriorityJobScheduler::queued()const{std::lock_guard l(mutex_);return queue_.size();}
} // namespace elysium::jobs
