#include "food/FoodRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
#include <set>
namespace elysium::food {namespace{bool hasTag(const InventoryLine&l,std::uint64_t t){return t&&std::find(l.tags.begin(),l.tags.end(),t)!=l.tags.end();}bool hasRegional(std::span<const std::uint64_t> tags,std::uint64_t t){return std::find(tags.begin(),tags.end(),t)!=tags.end();}}
bool FoodRuntime::publish(FoodDefinition d){if(!d.contentId||!std::isfinite(d.hunger)||!std::isfinite(d.saturation))return false;d.hunger=safe::nonNegative(d.hunger);d.saturation=safe::nonNegative(d.saturation);std::set<std::uint64_t>ids;for(auto&e:d.effects){if(!e.effectContentId||!e.durationTicks||!std::isfinite(e.magnitude)||!ids.insert(e.effectContentId).second)return false;e.magnitude=safe::nonNegative(e.magnitude);}return foods_.emplace(d.contentId,std::move(d)).second;}
bool FoodRuntime::publish(CuisineRecipe r){if(!r.recipeId||r.ingredients.empty()||r.outputs.empty())return false;for(const auto&i:r.ingredients)if(!i.quantity||(!i.contentId&&!i.requiredTagId))return false;for(const auto&o:r.outputs)if(!o.contentId||!o.quantity)return false;return recipes_.emplace(r.recipeId,std::move(r)).second;}
CookingReceipt FoodRuntime::cook(const CookingRequest&q){CookingReceipt out{};out.transactionId=q.transactionId;out.recipeId=q.recipeId;if(!q.transactionId){out.failure=CookingFailure::InvalidInput;return out;}if(processed_.contains(q.transactionId)){out.failure=CookingFailure::DuplicateTransaction;return out;}auto rit=recipes_.find(q.recipeId);if(rit==recipes_.end()){out.failure=CookingFailure::UnknownRecipe;return out;}const auto&r=rit->second;for(auto tag:r.requiredRegionalTags)if(!hasRegional(q.regionalTags,tag)){out.failure=CookingFailure::MissingRegionalTag;return out;}
 std::vector<std::uint64_t>remaining;remaining.reserve(q.inputs.size());for(const auto&line:q.inputs){if(!line.contentId||!line.quantity){out.failure=CookingFailure::InvalidInput;return out;}remaining.push_back(line.quantity);}for(const auto&req:r.ingredients){std::uint64_t need=req.quantity;for(std::size_t i=0;i<q.inputs.size()&&need;++i){const auto&line=q.inputs[i];const bool match=req.contentId?line.contentId==req.contentId:hasTag(line,req.requiredTagId);if(!match)continue;const auto take=std::min(need,remaining[i]);if(!take)continue;remaining[i]-=take;need-=take;InventoryLine used{line.contentId,take,line.tags};out.consumed.push_back(std::move(used));}if(need){out.failure=CookingFailure::MissingIngredient;return out;}}
 for(const auto&o:r.outputs){(o.agriculturalByproduct?out.byproducts:out.produced).push_back(o);}
 processed_[q.transactionId]=true;out.accepted=true;return out;}
FoodConsumptionIntent FoodRuntime::consume(std::uint64_t actor,std::uint64_t food)const{FoodConsumptionIntent out{};auto it=foods_.find(food);if(!actor||it==foods_.end())return out;out.actorId=actor;out.foodContentId=food;out.hunger=it->second.hunger;out.saturation=it->second.saturation;for(const auto&e:it->second.effects)out.effects.push_back({actor,food,e.effectContentId,e.kind,e.durationTicks,e.magnitude,e.stacking});return out;}
FoodEffectIntent FoodRuntime::combine(const FoodEffectIntent&a,const FoodEffectIntent&b){if(!a.effectContentId||a.effectContentId!=b.effectContentId||a.actorId!=b.actorId)return b;FoodEffectIntent o=b;switch(b.stacking){case EffectStackPolicy::RefreshDuration:o.magnitude=std::max(a.magnitude,b.magnitude);o.durationTicks=std::max(a.durationTicks,b.durationTicks);break;case EffectStackPolicy::ReplaceIfStronger:if(a.magnitude>b.magnitude)o=a;break;case EffectStackPolicy::AddMagnitude:o.magnitude=safe::nonNegative(a.magnitude+b.magnitude);o.durationTicks=std::max(a.durationTicks,b.durationTicks);break;}return o;}
FoodRuntimeSnapshot FoodRuntime::snapshot()const{FoodRuntimeSnapshot s;for(auto&[_,v]:foods_)s.foods.push_back(v);for(auto&[_,v]:recipes_)s.recipes.push_back(v);for(auto&[id,_]:processed_)s.processedTransactions.push_back(id);return s;}
bool FoodRuntime::restore(const FoodRuntimeSnapshot&s){FoodRuntime n;for(auto f:s.foods)if(!n.publish(std::move(f)))return false;for(auto r:s.recipes)if(!n.publish(std::move(r)))return false;for(auto id:s.processedTransactions)if(!id||!n.processed_.emplace(id,true).second)return false;*this=std::move(n);return true;}
} // namespace elysium::food
