#include "agriculture/CropRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
namespace elysium::agriculture {namespace{double unit(double v)noexcept{return safe::finiteClamp(v,0.0,1.0);}bool has(std::uint32_t mask,CultivationCapability c)noexcept{return(mask&capability(c))!=0;}}
bool CropRuntime::publish(CropDefinition d){if(!d.cropContentId||d.stageTicks.size()!=4||!d.waterUnitsPerStep||!std::isfinite(d.minimumLight)||!std::isfinite(d.minimumTemperature)||!std::isfinite(d.maximumTemperature)||!std::isfinite(d.minimumOxygen)||!std::isfinite(d.minimumPressure)||!std::isfinite(d.maximumWaterSaturation))return false;for(auto t:d.stageTicks)if(!t)return false;d.minimumLight=unit(d.minimumLight);d.minimumTemperature=unit(d.minimumTemperature);d.maximumTemperature=std::max(d.minimumTemperature,unit(d.maximumTemperature));d.minimumOxygen=unit(d.minimumOxygen);d.minimumPressure=unit(d.minimumPressure);d.maximumWaterSaturation=unit(d.maximumWaterSaturation);return defs_.emplace(d.cropContentId,std::move(d)).second;}
bool CropRuntime::createPlot(CropPlot p){if(!p.plotId||!defs_.contains(p.cropContentId)||!p.revision||p.stage==CropStage::Mature||p.stage==CropStage::Failed)return false;return plots_.emplace(p.plotId,std::move(p)).second;}
bool CropRuntime::commitMaterials(const MaterialCommit&c){if(!c.transactionId||transactions_.contains(c.transactionId))return false;auto it=plots_.find(c.plotId);if(it==plots_.end()||!it->second.live)return false;auto&p=it->second;p.waterUnits=safe::saturatingAdd(p.waterUnits,c.waterUnits);p.fertility.organic=safe::saturatingAdd(p.fertility.organic,c.organicUnits);p.fertility.mineral=safe::saturatingAdd(p.fertility.mineral,c.mineralUnits);p.fertility.precision=safe::saturatingAdd(p.fertility.precision,c.precisionUnits);p.revision=safe::saturatingIncrement(p.revision);transactions_[c.transactionId]=true;return true;}
CropInspection CropRuntime::inspect(std::uint64_t id,const CropEnvironment&e)const{CropInspection o{};o.plotId=id;auto it=plots_.find(id);if(it==plots_.end())return o;const auto&p=it->second;const auto&d=defs_.at(p.cropContentId);o.stage=p.stage;o.stageProgressTicks=p.stageProgressTicks;o.fertility=p.fertility;o.waterUnits=p.waterUnits;const std::size_t idx=std::min<std::size_t>(static_cast<std::size_t>(p.stage),3);o.stageRequiredTicks=d.stageTicks[idx];double suitability=unit(e.soilSuitability);if((p.capabilities&d.requiredCapabilities)!=d.requiredCapabilities)o.blockers|=blocker(CropBlocker::MissingCapability);if(e.flooded||unit(e.waterSaturation)>d.maximumWaterSaturation)o.blockers|=blocker(CropBlocker::Flooded);if(p.waterUnits<d.waterUnitsPerStep)o.blockers|=blocker(CropBlocker::Dry);if(p.fertility.organic<d.organicUnitsPerStep||p.fertility.mineral<d.mineralUnitsPerStep||p.fertility.precision<d.precisionUnitsPerStep)o.blockers|=blocker(CropBlocker::LowFertility);if(!std::isfinite(e.oxygen)||!std::isfinite(e.pressure)||unit(e.oxygen)<d.minimumOxygen||unit(e.pressure)<d.minimumPressure)o.blockers|=blocker(CropBlocker::InvalidAtmosphere);if(!std::isfinite(e.temperature)||unit(e.temperature)<d.minimumTemperature||unit(e.temperature)>d.maximumTemperature)o.blockers|=blocker(CropBlocker::Temperature);if(!std::isfinite(e.light)||unit(e.light)<d.minimumLight)o.blockers|=blocker(CropBlocker::Light);if(d.requiresSealedRoom&&!e.sealed&&!has(p.capabilities,CultivationCapability::ControlledEnvironment))o.blockers|=blocker(CropBlocker::MissingSeal);if(d.requiresPollination&&!e.pollinated)o.blockers|=blocker(CropBlocker::MissingPollination);if(has(p.capabilities,CultivationCapability::Greenhouse))suitability*=1.0+safe::nonNegative(e.greenhouseBonus,4.0);if(e.pollinated)suitability*=1.0+safe::nonNegative(e.pollinatorBonus,4.0);o.suitability=safe::finiteClamp(suitability,0.0,8.0);return o;}
bool CropRuntime::step(std::uint64_t id,const CropEnvironment&e,std::uint64_t ticks){if(!ticks||e.plotId!=id)return false;auto it=plots_.find(id);if(it==plots_.end()||!it->second.live)return false;auto&p=it->second;if(p.stage==CropStage::Mature||p.stage==CropStage::Failed)return true;const auto inspection=inspect(id,e);if(inspection.blockers!=0)return true;const auto&d=defs_.at(p.cropContentId);const std::uint64_t steps=std::max<std::uint64_t>(1,ticks);const auto waterNeed=safe::saturatingMultiply(d.waterUnitsPerStep,steps);const auto organicNeed=safe::saturatingMultiply(d.organicUnitsPerStep,steps);const auto mineralNeed=safe::saturatingMultiply(d.mineralUnitsPerStep,steps);const auto precisionNeed=safe::saturatingMultiply(d.precisionUnitsPerStep,steps);if(p.waterUnits<waterNeed||p.fertility.organic<organicNeed||p.fertility.mineral<mineralNeed||p.fertility.precision<precisionNeed)return true;p.waterUnits-=waterNeed;p.fertility.organic-=organicNeed;p.fertility.mineral-=mineralNeed;p.fertility.precision-=precisionNeed;const long double rawProgress=static_cast<long double>(ticks)*static_cast<long double>(inspection.suitability);const std::uint64_t progressed=rawProgress<=0.0L?std::uint64_t{0}:(rawProgress>=static_cast<long double>(std::numeric_limits<std::uint64_t>::max())?std::numeric_limits<std::uint64_t>::max():static_cast<std::uint64_t>(rawProgress));p.stageProgressTicks=safe::saturatingAdd<std::uint64_t>(p.stageProgressTicks,progressed);while(p.stage!=CropStage::Mature&&static_cast<std::size_t>(p.stage)<4){const auto need=d.stageTicks[static_cast<std::size_t>(p.stage)];if(p.stageProgressTicks<need)break;p.stageProgressTicks-=need;p.stage=static_cast<CropStage>(static_cast<std::uint8_t>(p.stage)+1);}p.revision=safe::saturatingIncrement(p.revision);return true;}
const CropPlot*CropRuntime::find(std::uint64_t id)const{auto it=plots_.find(id);return it==plots_.end()?nullptr:&it->second;}
CropSnapshot CropRuntime::snapshot()const{CropSnapshot s;for(auto&[_,v]:defs_)s.definitions.push_back(v);for(auto&[_,v]:plots_)s.plots.push_back(v);for(auto&[id,_]:transactions_)s.consumedTransactions.push_back(id);return s;}
bool CropRuntime::restore(const CropSnapshot&s){CropRuntime n;for(auto d:s.definitions)if(!n.publish(std::move(d)))return false;for(auto p:s.plots)if(!p.plotId||!p.revision||!n.defs_.contains(p.cropContentId)||!n.plots_.emplace(p.plotId,p).second)return false;for(auto id:s.consumedTransactions)if(!id||!n.transactions_.emplace(id,true).second)return false;*this=std::move(n);return true;}
} // namespace elysium::agriculture
