#include "agriculture/DomesticAnimalRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
#include <set>
namespace elysium::agriculture {namespace{
std::uint64_t mix64(std::uint64_t x) noexcept{x^=x>>30;x*=0xbf58476d1ce4e5b9ULL;x^=x>>27;x*=0x94d049bb133111ebULL;return x^(x>>31);}double unit(double v)noexcept{return safe::finiteClamp(v,0.0,1.0);}
}
bool DomesticAnimalRuntime::publish(DomesticArchetypeDefinition d){if(!d.contentId||!d.capabilityMask||!std::isfinite(d.hungerRate)||!std::isfinite(d.thirstRate)||!std::isfinite(d.shelterNeed))return false;d.hungerRate=unit(d.hungerRate);d.thirstRate=unit(d.thirstRate);d.shelterNeed=unit(d.shelterNeed);std::set<std::uint64_t>products;for(const auto&p:d.products){if(!p.productContentId||!p.quantity||!products.insert(p.productContentId).second)return false;if(p.trigger==ProductTrigger::Periodic&&!p.intervalTicks)return false;}return archetypes_.emplace(d.contentId,std::move(d)).second;}
bool DomesticAnimalRuntime::promote(const DomesticationTransaction&t){if(!t.transactionId||!t.sourceTransientActorId||!t.wildReconstructionKey||!t.newStableId||!t.ownerId||!archetypes_.contains(t.archetypeContentId)||transactions_.contains(t.transactionId)||animals_.contains(t.newStableId))return false;DomesticAnimalRecord a{};a.stableId=t.newStableId;a.ownerId=t.ownerId;a.archetypeContentId=t.archetypeContentId;a.nameRef=t.nameRef;a.wildReconstructionKey=t.wildReconstructionKey;a.productProgressTicks.assign(archetypes_.at(t.archetypeContentId).products.size(),0);animals_[a.stableId]=a;transactions_[t.transactionId]=true;return true;}
bool DomesticAnimalRuntime::applyCare(const DomesticCareInput&c){auto it=animals_.find(c.stableId);if(it==animals_.end()||!it->second.alive||!std::isfinite(c.feedCommit)||!std::isfinite(c.waterCommit)||!std::isfinite(c.shelterQuality))return false;auto&a=it->second;a.needs.hunger=unit(a.needs.hunger-safe::nonNegative(c.feedCommit));a.needs.thirst=unit(a.needs.thirst-safe::nonNegative(c.waterCommit));a.needs.shelter=unit(c.roomAvailable?c.shelterQuality:0.0);a.revision=safe::saturatingIncrement(a.revision);return true;}
void DomesticAnimalRuntime::emitProduct(DomesticAnimalRecord&a,const DomesticProductDefinition&p,std::size_t index,ProductTrigger trigger){auto id=mix64(a.stableId^mix64(p.productContentId)^mix64(a.revision)^mix64(static_cast<std::uint64_t>(index)+1));if(!id)id=1;while(pending_.contains(id))id=mix64(id+1);pending_[id]={id,a.stableId,p.productContentId,p.quantity,1,trigger};}
void DomesticAnimalRuntime::step(std::uint64_t ticks){if(!ticks)return;for(auto&[_,a]:animals_){if(!a.alive)continue;const auto&d=archetypes_.at(a.archetypeContentId);a.needs.hunger=unit(a.needs.hunger+d.hungerRate*static_cast<double>(ticks));a.needs.thirst=unit(a.needs.thirst+d.thirstRate*static_cast<double>(ticks));const double stress=std::max({a.needs.hunger,a.needs.thirst,std::max(0.0,d.shelterNeed-a.needs.shelter)});if(stress>=1.0)a.needs.health=unit(a.needs.health-0.001*static_cast<double>(ticks));for(std::size_t i=0;i<d.products.size();++i){const auto&p=d.products[i];if(p.trigger!=ProductTrigger::Periodic)continue;a.productProgressTicks[i]=safe::saturatingAdd(a.productProgressTicks[i],ticks);while(a.productProgressTicks[i]>=p.intervalTicks){a.productProgressTicks[i]-=p.intervalTicks;emitProduct(a,p,i,ProductTrigger::Periodic);}}a.revision=safe::saturatingIncrement(a.revision);}}
bool DomesticAnimalRuntime::retire(std::uint64_t id,std::uint64_t tx){auto it=animals_.find(id);if(it==animals_.end()||!tx||transactions_.contains(tx)||!it->second.alive)return false;auto&a=it->second;const auto&d=archetypes_.at(a.archetypeContentId);for(std::size_t i=0;i<d.products.size();++i)if(d.products[i].trigger==ProductTrigger::OnRetire)emitProduct(a,d.products[i],i,ProductTrigger::OnRetire);a.alive=false;a.revision=safe::saturatingIncrement(a.revision);transactions_[tx]=true;return true;}
const DomesticAnimalRecord*DomesticAnimalRuntime::find(std::uint64_t id)const{auto it=animals_.find(id);return it==animals_.end()?nullptr:&it->second;}
std::vector<ProductIntent>DomesticAnimalRuntime::pendingProducts()const{std::vector<ProductIntent>o;for(auto&[_,p]:pending_)o.push_back(p);return o;}
bool DomesticAnimalRuntime::acknowledgeProduct(std::uint64_t id){return pending_.erase(id)!=0;}
DomesticSnapshot DomesticAnimalRuntime::snapshot()const{DomesticSnapshot s;for(auto&[_,v]:archetypes_)s.archetypes.push_back(v);for(auto&[_,v]:animals_)s.animals.push_back(v);for(auto&[_,v]:pending_)s.pendingProducts.push_back(v);for(auto&[id,_]:transactions_)s.consumedDomesticationTransactions.push_back(id);return s;}
bool DomesticAnimalRuntime::restore(const DomesticSnapshot&s){DomesticAnimalRuntime n;for(auto d:s.archetypes)if(!n.publish(std::move(d)))return false;for(auto a:s.animals){if(!a.stableId||!a.ownerId||!a.revision||!n.archetypes_.contains(a.archetypeContentId)||a.productProgressTicks.size()!=n.archetypes_.at(a.archetypeContentId).products.size()||!n.animals_.emplace(a.stableId,a).second)return false;}for(auto p:s.pendingProducts)if(!p.intentId||!p.animalStableId||!p.productContentId||!p.quantity||!n.animals_.contains(p.animalStableId)||!n.pending_.emplace(p.intentId,p).second)return false;for(auto id:s.consumedDomesticationTransactions)if(!id||!n.transactions_.emplace(id,true).second)return false;*this=std::move(n);return true;}
} // namespace elysium::agriculture
