#include "exploration/CartographyRouteService.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
#include <limits>
#include <queue>
#include <set>
namespace elysium::exploration{
namespace{void norm(std::vector<std::uint64_t>&v){v.erase(std::remove(v.begin(),v.end(),0),v.end());std::sort(v.begin(),v.end());v.erase(std::unique(v.begin(),v.end()),v.end());}}
bool CartographyRouteService::publish(KnownChart c){if(!c.systemId)return false;c.knownSuspicion=elysium::safe::nonNegative(c.knownSuspicion);for(auto&r:c.resources){if(!r.resourceContentId)return false;r.abundanceLow=elysium::safe::nonNegative(r.abundanceLow);r.abundanceHigh=std::max(r.abundanceLow,elysium::safe::nonNegative(r.abundanceHigh));r.confidence=elysium::safe::finiteClamp(r.confidence,0.0,1.0);}std::sort(c.resources.begin(),c.resources.end(),[](auto&a,auto&b){return a.resourceContentId<b.resourceContentId;});norm(c.knownHazardContentIds);charts_[{c.systemId,c.planetId}]=std::move(c);return true;}bool CartographyRouteService::annotate(MapAnnotation a){if(!a.stableId||!a.systemId||!a.authorStableId)return false;annotations_[a.stableId]=a;return true;}bool CartographyRouteService::publish(KnownRouteEdge e){if(!e.fromSystemId||!e.toSystemId||e.fromSystemId==e.toSystemId||!e.known||!std::isfinite(e.distanceLy)||e.distanceLy<0)return false;e.hazardRisk=elysium::safe::nonNegative(e.hazardRisk);e.interdictionFriction=elysium::safe::nonNegative(e.interdictionFriction);auto key=std::minmax(e.fromSystemId,e.toSystemId);edges_[key]=e;return true;}bool CartographyRouteService::publish(RouteNodeKnowledge n){if(!n.systemId||!std::isfinite(n.suspicion)||n.suspicion<0)return false;n.suspicion=elysium::safe::nonNegative(n.suspicion);nodes_[n.systemId]=n;return true;}const KnownChart*CartographyRouteService::chart(std::uint64_t s,std::uint64_t p)const{auto i=charts_.find({s,p});return i==charts_.end()?nullptr:&i->second;}
std::vector<NeedMatch> CartographyRouteService::need(const NeedFilter&f)const{std::vector<NeedMatch>o;auto excluded=f.excludedHazards;norm(excluded);for(auto&[_,c]:charts_){if(f.requireAccessibleStation&&(!c.stationAccessKnown||!c.stationAccessible))continue;if(f.maximumKnownSuspicion&&(!c.suspicionKnown||c.knownSuspicion>*f.maximumKnownSuspicion))continue;if(std::any_of(excluded.begin(),excluded.end(),[&](auto h){return std::binary_search(c.knownHazardContentIds.begin(),c.knownHazardContentIds.end(),h);}))continue;if(f.resourceContentId){auto i=std::lower_bound(c.resources.begin(),c.resources.end(),*f.resourceContentId,[](auto&r,auto id){return r.resourceContentId<id;});if(i==c.resources.end()||i->resourceContentId!=*f.resourceContentId||i->confidence<f.minimumConfidence||i->abundanceLow<f.minimumAbundance)continue;o.push_back({c.systemId,c.planetId,i->abundanceLow,i->abundanceHigh,i->confidence});}else o.push_back({c.systemId,c.planetId,0,0,1});}std::sort(o.begin(),o.end(),[](auto&a,auto&b){return a.systemId<b.systemId||(a.systemId==b.systemId&&a.planetId<b.planetId);});return o;}
RouteEstimate CartographyRouteService::route(const RouteEstimateRequest&r)const{RouteEstimate o;if(!r.originSystemId||!r.destinationSystemId||!std::isfinite(r.jumpRangeLy)||r.jumpRangeLy<=0||!r.fuelCellsPerJump)return o;struct Q{double cost;std::uint64_t id;};struct C{bool operator()(const Q&a,const Q&b)const{return a.cost>b.cost||(a.cost==b.cost&&a.id>b.id);}};std::map<std::uint64_t,double>d,dist,risk;std::map<std::uint64_t,std::uint64_t>prev;std::priority_queue<Q,std::vector<Q>,C>q;d[r.originSystemId]=0;dist[r.originSystemId]=0;risk[r.originSystemId]=0;q.push({0,r.originSystemId});while(!q.empty()){auto x=q.top();q.pop();if(x.cost!=d[x.id])continue;if(x.id==r.destinationSystemId)break;for(auto&[_,e]:edges_){std::uint64_t n=0;if(e.fromSystemId==x.id)n=e.toSystemId;else if(e.toSystemId==x.id)n=e.fromSystemId;else continue;if(!e.activeGate&&e.distanceLy>r.jumpRangeLy)continue;double suspicion=0;auto ni=nodes_.find(n);if(ni!=nodes_.end()&&ni->second.suspicionKnown)suspicion=ni->second.suspicion;const double edgeRisk=elysium::safe::nonNegative(e.hazardRisk*r.hazardWeight+e.interdictionFriction*r.interdictionWeight+suspicion*r.suspicionWeight);const double edgeCost=(e.activeGate?0.001:e.distanceLy)+edgeRisk;const double nc=elysium::safe::nonNegative(x.cost+edgeCost);auto di=d.find(n);if(di==d.end()||nc<di->second||(nc==di->second&&x.id<prev[n])){d[n]=nc;dist[n]=elysium::safe::nonNegative(dist[x.id]+e.distanceLy);risk[n]=elysium::safe::nonNegative(risk[x.id]+edgeRisk);prev[n]=x.id;q.push({nc,n});}}}if(!d.contains(r.destinationSystemId))return o;std::vector<std::uint64_t>path;for(auto c=r.destinationSystemId;;c=prev[c]){path.push_back(c);if(c==r.originSystemId)break;if(!prev.contains(c))return RouteEstimate{};}std::reverse(path.begin(),path.end());const auto jumps=path.size()>1?static_cast<std::uint64_t>(path.size()-1):0;const auto fuel=elysium::safe::saturatingMultiply(jumps,r.fuelCellsPerJump);if(fuel>r.availableFuelCells)return o;o.found=true;o.systems=std::move(path);o.jumps=jumps;o.fuelCellsRequired=fuel;o.distanceLy=dist[r.destinationSystemId];o.risk=risk[r.destinationSystemId];o.cost=d[r.destinationSystemId];return o;}
} // namespace elysium::exploration
