#include "exploration/ResearchEvidenceRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
namespace elysium::exploration{
namespace{void normTags(std::vector<std::uint64_t>&v){v.erase(std::remove(v.begin(),v.end(),0),v.end());std::sort(v.begin(),v.end());v.erase(std::unique(v.begin(),v.end()),v.end());}bool containsAll(const std::vector<std::uint64_t>&have,const std::vector<std::uint64_t>&need){return std::includes(have.begin(),have.end(),need.begin(),need.end());}}
bool ResearchEvidenceRuntime::publish(ResearchUnlockDefinition d){if(!d.unlockContentId||!std::isfinite(d.minimumConfidence)||d.minimumConfidence<0||d.minimumConfidence>1)return false;normTags(d.requiredTagContentIds);definitions_[d.unlockContentId]=std::move(d);return true;}bool ResearchEvidenceRuntime::addEvidence(ResearchEvidenceEvent e){if(!e.stableEvidenceId||!e.sourceStableId||!e.points||!std::isfinite(e.confidence)||e.confidence<0||e.confidence>1||evidence_.contains(e.stableEvidenceId))return false;normTags(e.tagContentIds);evidence_[e.stableEvidenceId]=std::move(e);return true;}bool ResearchEvidenceRuntime::hasEvidence(std::uint64_t id)const{return evidence_.contains(id);}bool ResearchEvidenceRuntime::granted(std::uint64_t id)const{return granted_.contains(id);}std::uint64_t ResearchEvidenceRuntime::fieldPoints(ResearchDomain d)const{std::uint64_t p=0;for(auto&[_,e]:evidence_)if(e.domain==d)p=elysium::safe::saturatingAdd(p,e.points);return p;}
bool ResearchEvidenceRuntime::qualifies(const ResearchUnlockDefinition&d,std::uint64_t*out)const{std::uint64_t points=0;std::vector<std::uint64_t>allTags;for(auto&[_,e]:evidence_)if(e.domain==d.domain&&e.confidence>=d.minimumConfidence){points=elysium::safe::saturatingAdd(points,e.points);allTags.insert(allTags.end(),e.tagContentIds.begin(),e.tagContentIds.end());}normTags(allTags);if(out)*out=points;return points>=d.pointsRequired&&containsAll(allTags,d.requiredTagContentIds);}
ResearchEvaluation ResearchEvidenceRuntime::evaluate(std::uint32_t mask){ResearchEvaluation o;for(auto&[id,d]:definitions_){if(granted_.contains(id))continue;std::uint64_t p=0;if(!qualifies(d,&p))continue;if((mask&d.requiredProcessingMask)!=d.requiredProcessingMask){o.blockedUnlockContentIds.push_back(id);continue;}granted_.insert(id);o.newGrants.push_back({id,d.grantKind,d.domain,p});}return o;}
ResearchSnapshot ResearchEvidenceRuntime::snapshot()const{ResearchSnapshot s;for(auto&[_,d]:definitions_)s.definitions.push_back(d);for(auto&[_,e]:evidence_)s.evidence.push_back(e);s.grantedContentIds.assign(granted_.begin(),granted_.end());return s;}bool ResearchEvidenceRuntime::restore(const ResearchSnapshot&s){ResearchEvidenceRuntime r;for(auto d:s.definitions)if(!r.publish(std::move(d)))return false;for(auto e:s.evidence)if(!r.addEvidence(std::move(e)))return false;for(auto id:s.grantedContentIds){if(!id||!r.definitions_.contains(id)||r.granted_.contains(id))return false;r.granted_.insert(id);}*this=std::move(r);return true;}
} // namespace elysium::exploration
