#include "exploration/ScanCatalogueRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
namespace elysium::exploration{
bool ScanCatalogueRuntime::publish(ScanDefinition d){if(!d.contentId||!std::isfinite(d.baseRangeMeters)||d.baseRangeMeters<0||!std::isfinite(d.energyCost)||d.energyCost<0)return false;definitions_[d.contentId]=d;return true;}bool ScanCatalogueRuntime::publish(ScannerAccount s){if(!s.stableId||!std::isfinite(s.energy)||s.energy<0)return false;s.energy=elysium::safe::nonNegative(s.energy);scanners_[s.stableId]=s;return true;}const ScannerAccount*ScanCatalogueRuntime::scanner(std::uint64_t id)const{auto i=scanners_.find(id);return i==scanners_.end()?nullptr:&i->second;}const CatalogueRecord*ScanCatalogueRuntime::known(std::uint64_t id)const{auto i=catalogue_.find(id);return i==catalogue_.end()?nullptr:&i->second;}
ScanOutcome ScanCatalogueRuntime::attempt(std::uint64_t defId,std::uint64_t scannerId,const ScanSubject&s,const ScanModifiers&m){ScanOutcome o;auto di=definitions_.find(defId);if(di==definitions_.end()){o.block=ScanBlock::MissingDefinition;return o;}auto ai=scanners_.find(scannerId);if(ai==scanners_.end()){o.block=ScanBlock::MissingScanner;return o;}const auto&d=di->second;auto&acct=ai->second;auto fail=[&](ScanBlock b){o.block=b;if(d.spendOnBlocked){const auto e=std::min(acct.energy,d.energyCost);const auto c=std::min(acct.charges,d.chargeCost);acct.energy=elysium::safe::nonNegative(acct.energy-e);acct.charges-=c;acct.revision=elysium::safe::saturatingIncrement(acct.revision);o.energySpent=e;o.chargesSpent=c;}return o;};if(!s.stableTargetId||!std::isfinite(s.distanceMeters)||s.distanceMeters<0)return fail(ScanBlock::InvalidTarget);if(s.kind!=d.kind)return fail(ScanBlock::WrongKind);if(catalogue_.contains(s.stableTargetId))return fail(ScanBlock::AlreadyCatalogued);if((m.toolMask&d.requiredToolMask)!=d.requiredToolMask)return fail(ScanBlock::MissingTool);if((m.knowledgeMask&d.requiredKnowledgeMask)!=d.requiredKnowledgeMask)return fail(ScanBlock::MissingKnowledge);if(!std::isfinite(m.equipmentRangeMultiplier)||!std::isfinite(m.relayRangeMultiplier)||m.equipmentRangeMultiplier<0||m.relayRangeMultiplier<0)return fail(ScanBlock::InvalidTarget);o.effectiveRangeMeters=elysium::safe::nonNegative(d.baseRangeMeters*m.equipmentRangeMultiplier*m.relayRangeMultiplier);if(s.distanceMeters>o.effectiveRangeMeters)return fail(ScanBlock::OutOfRange);if(d.requiresLineOfSight&&!s.lineOfSight)return fail(ScanBlock::NoLineOfSight);if(acct.energy+1e-9<d.energyCost)return fail(ScanBlock::InsufficientEnergy);if(acct.charges<d.chargeCost)return fail(ScanBlock::InsufficientCharges);acct.energy=elysium::safe::nonNegative(acct.energy-d.energyCost);acct.charges-=d.chargeCost;acct.revision=elysium::safe::saturatingIncrement(acct.revision);o.energySpent=d.energyCost;o.chargesSpent=d.chargeCost;const auto confidence=elysium::safe::finiteClamp(m.interpretationMultiplier,0.0,1.0);CatalogueRecord r{s.stableTargetId,d.contentId,scannerId,d.knownFieldMask,1,s.kind,confidence};catalogue_[s.stableTargetId]=r;o.record=r;o.marker={s.stableTargetId,s.kind,confidence};o.accepted=true;o.block=ScanBlock::None;return o;}
ScanSnapshot ScanCatalogueRuntime::snapshot()const{ScanSnapshot s;for(auto&[_,x]:definitions_)s.definitions.push_back(x);for(auto&[_,x]:scanners_)s.scanners.push_back(x);for(auto&[_,x]:catalogue_)s.catalogue.push_back(x);return s;}bool ScanCatalogueRuntime::restore(const ScanSnapshot&s){ScanCatalogueRuntime r;for(auto x:s.definitions)if(!r.publish(x))return false;for(auto x:s.scanners)if(!r.publish(x))return false;for(auto x:s.catalogue){if(!x.stableTargetId||!x.scanDefinitionContentId||!r.definitions_.contains(x.scanDefinitionContentId)||r.catalogue_.contains(x.stableTargetId))return false;r.catalogue_[x.stableTargetId]=x;}*this=std::move(r);return true;}
} // namespace elysium::exploration
