#include "poi/PoiLootRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
namespace elysium::poi{namespace{std::uint64_t mix(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}std::uint64_t seed(const PoiLootKey&k){return mix(k.worldSeed^mix(k.siteStableId)^mix(k.objectStableId)^mix(k.poolContentId));}}
bool PoiLootRuntime::approveReward(std::uint64_t id){if(!id)return false;approved_.insert(id);return true;}
PoiLootFailure PoiLootRuntime::publish(PoiLootPool p){if(!p.contentId||p.entries.empty())return PoiLootFailure::UnknownPool;std::sort(p.entries.begin(),p.entries.end(),[](auto&a,auto&b){return a.rewardContentId<b.rewardContentId;});for(auto&e:p.entries)if(!e.rewardContentId||!e.weight||!e.minimumCount||e.minimumCount>e.maximumCount||!approved_.contains(e.rewardContentId))return PoiLootFailure::UnapprovedReward;pools_[p.contentId]=std::move(p);return PoiLootFailure::None;}
PoiLootFailure PoiLootRuntime::begin(PoiLootTransaction t){if(!t.stableId||!t.actorStableId||!t.key.worldSeed||!t.key.siteStableId||!t.key.objectStableId||!pools_.contains(t.key.poolContentId))return PoiLootFailure::InvalidObject;if(transactions_.contains(t.stableId))return PoiLootFailure::DuplicateTransaction;if(t.key.provenance!=PoiObjectProvenance::GeneratedAuthored)return PoiLootFailure::ProvenanceRejected;auto o=objects_.find(t.key.objectStableId);if(o!=objects_.end()&&(o->second.consumed||o->second.tombstoned))return PoiLootFailure::AlreadyConsumed;transactions_[t.stableId]=t;return PoiLootFailure::None;}
std::vector<RewardGrant>PoiLootRuntime::roll(const PoiLootKey&k)const{std::vector<RewardGrant>o;auto i=pools_.find(k.poolContentId);if(i==pools_.end())return o;std::uint64_t total=0;for(auto&e:i->second.entries)total=elysium::safe::saturatingAdd(total,e.weight);if(!total)return o;auto h=seed(k);const auto pick=h%total;std::uint64_t c=0;for(auto&e:i->second.entries){c=elysium::safe::saturatingAdd(c,e.weight);if(pick<c){const auto span=e.maximumCount-e.minimumCount+1;const auto n=e.minimumCount+((h>>32)%span);o.push_back({e.rewardContentId,n});break;}}return o;}
PoiLootOutcome PoiLootRuntime::commit(std::uint64_t id){PoiLootOutcome o;auto i=transactions_.find(id);if(i==transactions_.end()||i->second.state!=PoiInteractionState::Requested){o.failure=PoiLootFailure::InvalidState;return o;}auto&t=i->second;auto&state=objects_[t.key.objectStableId];if(state.objectStableId==0)state.objectStableId=t.key.objectStableId;if(state.consumed||state.tombstoned){o.failure=PoiLootFailure::AlreadyConsumed;return o;}if(t.kind==PoiInteractionKind::Open)o.rewards=roll(t.key);if(t.kind==PoiInteractionKind::Open||t.kind==PoiInteractionKind::Destroy){state.consumed=true;state.tombstoned=true;}state.revision=elysium::safe::saturatingIncrement(state.revision);t.state=PoiInteractionState::Committed;t.revision=elysium::safe::saturatingIncrement(t.revision);o.committed=true;o.effects.push_back({PoiSideEffectKind::Discovery,t.key.objectStableId,t.key.poolContentId,1});return o;}
bool PoiLootRuntime::rollback(std::uint64_t id){auto i=transactions_.find(id);if(i==transactions_.end()||i->second.state!=PoiInteractionState::Requested)return false;i->second.state=PoiInteractionState::RolledBack;i->second.revision=elysium::safe::saturatingIncrement(i->second.revision);return true;}
const PoiLootObjectState*PoiLootRuntime::objectState(std::uint64_t id)const{auto i=objects_.find(id);return i==objects_.end()?nullptr:&i->second;}
PoiLootSnapshot PoiLootRuntime::snapshot()const{PoiLootSnapshot s;for(auto&[_,p]:pools_)s.pools.push_back(p);s.approvedRewardIds.assign(approved_.begin(),approved_.end());for(auto&[_,t]:transactions_)s.transactions.push_back(t);for(auto&[_,o]:objects_)s.touchedObjects.push_back(o);return s;}
bool PoiLootRuntime::restore(const PoiLootSnapshot&s){PoiLootRuntime r;for(auto id:s.approvedRewardIds)if(!r.approveReward(id))return false;for(auto p:s.pools)if(r.publish(std::move(p))!=PoiLootFailure::None)return false;for(auto t:s.transactions){if(!t.stableId||r.transactions_.contains(t.stableId)||!r.pools_.contains(t.key.poolContentId))return false;r.transactions_[t.stableId]=t;}for(auto o:s.touchedObjects){if(!o.objectStableId||r.objects_.contains(o.objectStableId))return false;r.objects_[o.objectStableId]=o;}*this=std::move(r);return true;}
} // namespace elysium::poi
