#include "logistics/BaseLogisticsRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
namespace elysium::logistics { namespace{constexpr std::uint64_t Provider=0x4c4f474953ULL;}
static std::uint64_t used(const NetworkStorageNode&n){std::uint64_t v=0;for(const auto&s:n.stacks)v=safe::saturatingAdd(v,s.count);return v;}
static std::uint64_t countOf(const NetworkStorageNode&n,ContentId id){std::uint64_t v=0;for(const auto&s:n.stacks)if(s.itemId==id)v=safe::saturatingAdd(v,s.count);return v;}
bool BaseLogisticsRuntime::upsertStorage(NetworkStorageNode n){if(n.nodeId==0||n.baseId==0)return false;std::sort(n.stacks.begin(),n.stacks.end(),[](auto&a,auto&b){return a.itemId<b.itemId;});nodes_[n.nodeId]=std::move(n);return true;}
bool BaseLogisticsRuntime::upsertEdge(TransportEdge e){if(e.edgeId==0||e.sourceNode==0||e.targetNode==0||e.baseId==0)return false;e.unitsPerSecond=safe::nonNegative(e.unitsPerSecond);edges_[e.edgeId]=e;return true;}
const NetworkStorageNode*BaseLogisticsRuntime::storage(StableId id)const{auto it=nodes_.find(id);return it==nodes_.end()?nullptr:&it->second;}
TransferPlan BaseLogisticsRuntime::plan(const TransferRequest&r)const{TransferPlan out{};if(r.transactionId==0||r.baseId==0||r.itemId==0||r.count==0){out.reasons.add({reason::ReasonCode::InvalidRequest,Provider,r.transactionId,0});return out;}if(transactions_.contains(r.transactionId)){out.reasons.add({reason::ReasonCode::DuplicateTransaction,Provider,r.transactionId,5});return out;}auto a=nodes_.find(r.sourceNode),b=nodes_.find(r.targetNode);if(a==nodes_.end()||b==nodes_.end()){out.reasons.add({reason::ReasonCode::UnknownContent,Provider,r.sourceNode,10});return out;}if(a->second.baseId!=r.baseId||b->second.baseId!=r.baseId){out.reasons.add({reason::ReasonCode::InvalidRequest,Provider,r.baseId,15});return out;}if(!a->second.powered||!b->second.powered){out.reasons.add({reason::ReasonCode::InsufficientPower,Provider,r.baseId,20});return out;}auto avail=countOf(a->second,r.itemId);auto room=b->second.capacityUnits>used(b->second)?b->second.capacityUnits-used(b->second):0;out.count=std::min({r.count,avail,room});if(out.count==0)out.reasons.add({avail?reason::ReasonCode::OutputBlocked:reason::ReasonCode::MissingInput,Provider,r.itemId,30});out.accepted=!out.reasons.blocked();return out;}
bool BaseLogisticsRuntime::commit(const TransferRequest&r,const TransferPlan&p){if(!p.accepted||p.count==0||transactions_.contains(r.transactionId))return false;auto a=nodes_.find(r.sourceNode),b=nodes_.find(r.targetNode);if(a==nodes_.end()||b==nodes_.end()||a->second.baseId!=r.baseId||b->second.baseId!=r.baseId)return false;auto*src=&a->second;auto*dst=&b->second;std::uint64_t remain=p.count;for(auto&st:src->stacks)if(st.itemId==r.itemId){auto take=std::min(st.count,remain);st.count-=take;remain-=take;if(!remain)break;}if(remain)return false;auto it=std::lower_bound(dst->stacks.begin(),dst->stacks.end(),r.itemId,[](const auto&s,ContentId id){return s.itemId<id;});if(it!=dst->stacks.end()&&it->itemId==r.itemId)it->count=safe::saturatingAdd(it->count,p.count);else dst->stacks.insert(it,{r.itemId,p.count});src->stacks.erase(std::remove_if(src->stacks.begin(),src->stacks.end(),[](auto&s){return s.count==0;}),src->stacks.end());transactions_.insert(r.transactionId);return true;}
std::vector<NetworkStorageNode>BaseLogisticsRuntime::snapshot()const{std::vector<NetworkStorageNode>o;for(auto&[_,n]:nodes_)o.push_back(n);std::sort(o.begin(),o.end(),[](auto&a,auto&b){return a.nodeId<b.nodeId;});return o;}
} // namespace elysium::logistics
