#include "travel/ShipCargoTransferRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>

namespace elysium::travel {
namespace {
void normalize(CargoEndpoint&e){std::sort(e.stacks.begin(),e.stacks.end(),[](const auto&a,const auto&b){return a.itemStableId<b.itemStableId;});std::vector<CargoStack>o;for(auto s:e.stacks){if(!s.itemStableId||!s.contentId||!s.count)continue;if(!o.empty()&&o.back().itemStableId==s.itemStableId&&o.back().contentId==s.contentId)o.back().count=elysium::safe::saturatingAdd(o.back().count,s.count);else o.push_back(s);}e.stacks=std::move(o);}
std::uint64_t used(const CargoEndpoint&e){std::uint64_t n=0;for(const auto&s:e.stacks)n=elysium::safe::saturatingAdd(n,s.count);return n;}
CargoStack* stack(CargoEndpoint&e,std::uint64_t id){auto i=std::find_if(e.stacks.begin(),e.stacks.end(),[&](const auto&s){return s.itemStableId==id;});return i==e.stacks.end()?nullptr:&*i;}
const CargoStack* stack(const CargoEndpoint&e,std::uint64_t id){auto i=std::find_if(e.stacks.begin(),e.stacks.end(),[&](const auto&s){return s.itemStableId==id;});return i==e.stacks.end()?nullptr:&*i;}
}
bool ShipCargoTransferRuntime::publishEndpoint(CargoEndpoint e){if(!e.stableId||!e.ownerStableId||!e.capacity)return false;normalize(e);if(used(e)>e.capacity)return false;endpoints_[e.stableId]=std::move(e);return true;}
bool ShipCargoTransferRuntime::createTransfer(CargoTransferTransaction t){if(!t.stableId||!t.authorStableId||!t.sourceEndpointId||!t.destinationEndpointId||t.sourceEndpointId==t.destinationEndpointId||!t.itemStableId||!t.contentId||!t.requestedCount||transactions_.contains(t.stableId))return false;t.movedCount=0;t.revision=1;t.state=CargoTransferState::Requested;t.lastFailure=CargoTransferFailure::None;transactions_[t.stableId]=t;return true;}
bool ShipCargoTransferRuntime::endpointLocked(std::uint64_t id,std::uint64_t excluding)const{for(const auto&[tid,t]:transactions_)if(tid!=excluding&&(t.sourceEndpointId==id||t.destinationEndpointId==id)&&(t.state==CargoTransferState::Reserved||t.state==CargoTransferState::InProgress||t.state==CargoTransferState::Paused))return true;return false;}
CargoTransferFailure ShipCargoTransferRuntime::reserve(std::uint64_t id){auto ti=transactions_.find(id);if(ti==transactions_.end())return CargoTransferFailure::InvalidRequest;auto& t=ti->second;auto si=endpoints_.find(t.sourceEndpointId),di=endpoints_.find(t.destinationEndpointId);if(si==endpoints_.end()||di==endpoints_.end())return t.lastFailure=CargoTransferFailure::MissingEndpoint;auto&s=si->second;auto&d=di->second;if(endpointLocked(s.stableId,id)||endpointLocked(d.stableId,id))return t.lastFailure=CargoTransferFailure::EndpointBusy;if(!s.available||!d.available)return t.lastFailure=CargoTransferFailure::DockUnavailable;if(t.authorStableId!=s.ownerStableId&&t.authorStableId!=d.ownerStableId)return t.lastFailure=CargoTransferFailure::PermissionDenied;if((s.kind==CargoEndpointKind::BaseLocalNetworkStorage||d.kind==CargoEndpointKind::BaseLocalNetworkStorage)&&(!s.baseStableId||!d.baseStableId||s.baseStableId!=d.baseStableId))return t.lastFailure=CargoTransferFailure::BaseBoundaryViolation;const auto*ss=stack(s,t.itemStableId);if(!ss||ss->contentId!=t.contentId||ss->count<t.requestedCount)return t.lastFailure=CargoTransferFailure::MissingCargo;const auto room=d.capacity-used(d);if(room<t.requestedCount)return t.lastFailure=CargoTransferFailure::CapacityExceeded;t.state=CargoTransferState::Reserved;t.lastFailure=CargoTransferFailure::None;t.revision=elysium::safe::saturatingIncrement(t.revision);event(CargoEventKind::TransferStarted,id,s.stableId,d.stableId,0);return CargoTransferFailure::None;}
CargoTransferFailure ShipCargoTransferRuntime::step(std::uint64_t id,std::uint64_t maxCount){auto ti=transactions_.find(id);if(ti==transactions_.end()||!maxCount)return CargoTransferFailure::InvalidRequest;auto&t=ti->second;if(t.state!=CargoTransferState::Reserved&&t.state!=CargoTransferState::InProgress&&t.state!=CargoTransferState::Paused)return CargoTransferFailure::InvalidRequest;auto& s=endpoints_.at(t.sourceEndpointId);auto& d=endpoints_.at(t.destinationEndpointId);if(!s.available||!d.available){t.state=CargoTransferState::Paused;t.lastFailure=CargoTransferFailure::DockUnavailable;event(CargoEventKind::TransferPaused,id,s.stableId,d.stableId,0);return t.lastFailure;}if(!s.powered||!d.powered){t.state=CargoTransferState::Paused;t.lastFailure=CargoTransferFailure::Brownout;event(CargoEventKind::TransferPaused,id,s.stableId,d.stableId,0);return t.lastFailure;}auto*ss=stack(s,t.itemStableId);if(!ss||ss->contentId!=t.contentId)return t.lastFailure=CargoTransferFailure::MissingCargo;const auto remaining=t.requestedCount-t.movedCount;const auto room=d.capacity-used(d);const auto n=std::min({remaining,maxCount,ss->count,room});if(!n)return t.lastFailure=(room?CargoTransferFailure::MissingCargo:CargoTransferFailure::CapacityExceeded);ss->count-=n;if(ss->count==0){s.stacks.erase(std::remove_if(s.stacks.begin(),s.stacks.end(),[&](const auto&x){return x.itemStableId==t.itemStableId;}),s.stacks.end());}auto*ds=stack(d,t.itemStableId);if(ds)ds->count=elysium::safe::saturatingAdd(ds->count,n);else d.stacks.push_back({t.itemStableId,t.contentId,n});normalize(d);t.movedCount=elysium::safe::saturatingAdd(t.movedCount,n);t.revision=elysium::safe::saturatingIncrement(t.revision);t.state=t.movedCount==t.requestedCount?CargoTransferState::Completed:CargoTransferState::InProgress;t.lastFailure=CargoTransferFailure::None;if(t.state==CargoTransferState::Completed)event(CargoEventKind::TransferCompleted,id,d.stableId,s.stableId,t.movedCount);return CargoTransferFailure::None;}
bool ShipCargoTransferRuntime::cancel(std::uint64_t id){auto it=transactions_.find(id);if(it==transactions_.end()||it->second.state==CargoTransferState::Completed||it->second.state==CargoTransferState::Cancelled)return false;it->second.state=CargoTransferState::Cancelled;it->second.revision=elysium::safe::saturatingIncrement(it->second.revision);event(CargoEventKind::TransferCancelled,id,it->second.sourceEndpointId,it->second.destinationEndpointId,it->second.movedCount);return true;}
bool ShipCargoTransferRuntime::setEndpointPower(std::uint64_t id,bool p){auto i=endpoints_.find(id);if(i==endpoints_.end())return false;i->second.powered=p;return true;}bool ShipCargoTransferRuntime::setEndpointAvailability(std::uint64_t id,bool a){auto i=endpoints_.find(id);if(i==endpoints_.end())return false;i->second.available=a;return true;}
void ShipCargoTransferRuntime::event(CargoEventKind k,std::uint64_t t,std::uint64_t e,std::uint64_t r,std::uint64_t n){events_.push_back({nextEventSequence_,k,t,e,r,n});nextEventSequence_=elysium::safe::saturatingIncrement(nextEventSequence_);}void ShipCargoTransferRuntime::emitArrival(std::uint64_t e,std::uint64_t r){event(CargoEventKind::Arrival,0,e,r,0);}void ShipCargoTransferRuntime::emitDeparture(std::uint64_t e,std::uint64_t r){event(CargoEventKind::Departure,0,e,r,0);}
const CargoEndpoint* ShipCargoTransferRuntime::endpoint(std::uint64_t id)const{auto i=endpoints_.find(id);return i==endpoints_.end()?nullptr:&i->second;}const CargoTransferTransaction* ShipCargoTransferRuntime::transaction(std::uint64_t id)const{auto i=transactions_.find(id);return i==transactions_.end()?nullptr:&i->second;}
CargoTransferSnapshot ShipCargoTransferRuntime::snapshot()const{CargoTransferSnapshot s;s.nextEventSequence=nextEventSequence_;for(const auto&[_,e]:endpoints_)s.endpoints.push_back(e);for(const auto&[_,t]:transactions_)s.transactions.push_back(t);return s;}
bool ShipCargoTransferRuntime::restore(const CargoTransferSnapshot&s){ShipCargoTransferRuntime staged;for(auto e:s.endpoints)if(!staged.publishEndpoint(std::move(e)))return false;for(auto t:s.transactions){if(!t.stableId||!staged.endpoints_.contains(t.sourceEndpointId)||!staged.endpoints_.contains(t.destinationEndpointId)||staged.transactions_.contains(t.stableId))return false;staged.transactions_[t.stableId]=t;}staged.nextEventSequence_=std::max<std::uint64_t>(1,s.nextEventSequence);*this=std::move(staged);return true;}
} // namespace elysium::travel
