#include "travel/ShipFrameRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
#include <cmath>
#include <set>
namespace elysium::travel {
bool ShipFrameRuntime::publish(ShipFrameDefinition d){if(!d.contentId||!std::isfinite(d.hull)||!std::isfinite(d.atmosphericHandling)||d.hull<=0)return false;std::set<unsigned>domains;for(auto&s:d.slots)if(!s.slots||!domains.insert(static_cast<unsigned>(s.domain)).second)return false;d.hull=safe::nonNegative(d.hull);d.atmosphericHandling=safe::nonNegative(d.atmosphericHandling);return frames_.emplace(d.contentId,std::move(d)).second;}
bool ShipFrameRuntime::publish(ShipModuleDefinition d){if(!d.contentId||!d.slotCost||!std::isfinite(d.hullBonus)||!std::isfinite(d.handlingBonus)||d.hullBonus<0||d.handlingBonus<0)return false;return modules_.emplace(d.contentId,d).second;}
bool ShipFrameRuntime::publish(JumpTierDefinition d){if(!d.tier||!d.fuelCellsPerJump||!std::isfinite(d.maximumRangeLy)||d.maximumRangeLy<=0)return false;d.maximumRangeLy=safe::nonNegative(d.maximumRangeLy);return tiers_.emplace(d.tier,d).second;}
bool ShipFrameRuntime::create(ShipState s){if(!s.stableId||!s.frameContentId||!s.revision||!frames_.contains(s.frameContentId)||!std::isfinite(s.hull))return false;auto statsFrame=frames_.at(s.frameContentId);if(s.hull<=0)s.hull=statsFrame.hull;if(s.fuelCells>statsFrame.fuelCellCapacity)s.fuelCells=statsFrame.fuelCellCapacity;return ships_.emplace(s.stableId,std::move(s)).second;}
ShipDerivedStats ShipFrameRuntime::derive(std::uint64_t id)const{ShipDerivedStats o{};auto sit=ships_.find(id);if(sit==ships_.end())return o;auto fit=frames_.find(sit->second.frameContentId);if(fit==frames_.end())return o;const auto&f=fit->second;o.cargoCapacity=f.cargoCapacity;o.fuelCellCapacity=f.fuelCellCapacity;o.maximumHull=f.hull;o.atmosphericHandling=f.atmosphericHandling;o.scannerGrade=f.scannerGrade;o.jumpTier=f.baseJumpTier;std::map<ShipSlotDomain,std::uint64_t>capacity,used;for(auto&s:f.slots)capacity[s.domain]=s.slots;std::set<std::uint64_t>seenItems;auto installed=sit->second.modules;std::sort(installed.begin(),installed.end(),[](auto&a,auto&b){return a.stableItemId<b.stableItemId;});for(auto&i:installed){if(!i.stableItemId||!i.moduleContentId||!seenItems.insert(i.stableItemId).second)return {};auto mit=modules_.find(i.moduleContentId);if(mit==modules_.end())return {};const auto&m=mit->second;used[m.domain]=safe::saturatingAdd(used[m.domain],static_cast<std::uint64_t>(m.slotCost));if(used[m.domain]>capacity[m.domain])return {};if(!i.enabled)continue;o.cargoCapacity=safe::saturatingAdd(o.cargoCapacity,m.cargoBonus);o.fuelCellCapacity=safe::saturatingAdd(o.fuelCellCapacity,m.fuelBonus);o.maximumHull=safe::nonNegative(o.maximumHull+m.hullBonus);o.atmosphericHandling=safe::nonNegative(o.atmosphericHandling+m.handlingBonus);o.scannerGrade=safe::saturatingAdd(o.scannerGrade,m.scannerBonus);o.jumpTier=std::max(o.jumpTier,m.jumpTier);o.capabilities|=m.capabilities;}auto tit=tiers_.find(o.jumpTier);if(tit!=tiers_.end())o.jumpRangeLy=tit->second.maximumRangeLy;o.valid=true;return o;}
bool ShipFrameRuntime::setModules(std::uint64_t id,std::vector<InstalledShipModule>m){auto it=ships_.find(id);if(it==ships_.end())return false;auto old=it->second.modules;it->second.modules=std::move(m);if(!derive(id).valid){it->second.modules=std::move(old);return false;}it->second.revision=safe::saturatingIncrement(it->second.revision);return true;}
bool ShipFrameRuntime::migrateFrame(std::uint64_t id,std::uint64_t frame){auto it=ships_.find(id);if(it==ships_.end()||!frames_.contains(frame))return false;auto old=it->second.frameContentId;it->second.frameContentId=frame;auto d=derive(id);if(!d.valid){it->second.frameContentId=old;return false;}it->second.fuelCells=std::min(it->second.fuelCells,d.fuelCellCapacity);it->second.hull=std::min(safe::nonNegative(it->second.hull),d.maximumHull);it->second.revision=safe::saturatingIncrement(it->second.revision);return true;}
const ShipState*ShipFrameRuntime::find(std::uint64_t id)const{auto it=ships_.find(id);return it==ships_.end()?nullptr:&it->second;}
ShipCheck ShipFrameRuntime::checkJump(std::uint64_t id,double distance)const{ShipCheck c{};if(!std::isfinite(distance)||distance<0){c.reason=ShipBlockReason::InvalidDistance;return c;}auto sit=ships_.find(id);if(sit==ships_.end()){c.reason=ShipBlockReason::MissingShip;return c;}auto d=derive(id);if(!d.valid){c.reason=ShipBlockReason::MalformedModule;return c;}auto tit=tiers_.find(d.jumpTier);if(tit==tiers_.end()){c.reason=ShipBlockReason::MissingWarpTier;return c;}c.fuelRequired=tit->second.fuelCellsPerJump;c.maximumRangeLy=tit->second.maximumRangeLy;if(distance>c.maximumRangeLy){c.reason=ShipBlockReason::RangeExceeded;return c;}if(sit->second.fuelCells<c.fuelRequired){c.reason=ShipBlockReason::InsufficientFuel;return c;}c.allowed=true;return c;}
ShipSnapshot ShipFrameRuntime::snapshot()const{ShipSnapshot s;for(auto&[_,v]:frames_)s.frames.push_back(v);for(auto&[_,v]:modules_)s.modules.push_back(v);for(auto&[_,v]:tiers_)s.jumpTiers.push_back(v);for(auto&[_,v]:ships_)s.ships.push_back(v);return s;}
bool ShipFrameRuntime::restore(const ShipSnapshot&s){ShipFrameRuntime n;for(auto v:s.frames)if(!n.publish(std::move(v)))return false;for(auto v:s.modules)if(!n.publish(v))return false;for(auto v:s.jumpTiers)if(!n.publish(v))return false;for(auto v:s.ships)if(!n.create(std::move(v)))return false;for(auto&[id,_]:n.ships_)if(!n.derive(id).valid)return false;*this=std::move(n);return true;}
} // namespace elysium::travel
