#include "anomaly/BiomeRuleModifier.hpp"
#include <algorithm>
#include <cmath>
namespace elysium::anomaly {namespace{std::uint64_t mix(std::uint64_t x){x^=x>>30;x*=0xbf58476d1ce4e5b9ULL;x^=x>>27;x*=0x94d049bb133111ebULL;return x^(x>>31);}double unit(std::uint64_t x){return double(mix(x)&0xFFFFFFULL)/double(0xFFFFFFULL);}double clamp(double v,double lo,double hi){if(!std::isfinite(v))return 1.0;return std::clamp(v,lo,hi);} }
Region generatedRegion(std::uint64_t seed,ContentId biome,std::uint64_t key,std::uint32_t ordinal,std::uint32_t)noexcept{auto b=mix(seed^mix(biome)^mix(key)^ordinal);Region r{};r.regionId=mix(b^0xA11AULL);r.biomeId=biome;r.spatialKey=key;r.priority=std::uint32_t(mix(b^1)&15);r.gravityScale=.65+unit(b^2)*.7;r.gravityBiasX=(unit(b^3)-.5)*.3;r.gravityBiasY=(unit(b^4)-.5)*.3;r.gravityBiasZ=(unit(b^5)-.5)*.3;r.traversalScale=.65+unit(b^6)*1.2;r.scannerReliability=.45+unit(b^7)*.55;r.scannerContradiction=unit(b^8)*.35;r.hazardScale=.7+unit(b^9)*1.4;return r;}
Query evaluate(std::vector<Region> r){std::sort(r.begin(),r.end(),[](auto&a,auto&b){if(a.priority!=b.priority)return a.priority>b.priority;return a.regionId<b.regionId;});Query q{};for(auto&x:r){if(!x.regionId)continue;q.activeRegions.push_back(x.regionId);q.gravityScale=clamp(q.gravityScale*clamp(x.gravityScale,.1,10),.1,10);q.gravityBiasX=clamp(q.gravityBiasX+x.gravityBiasX,-4,4);q.gravityBiasY=clamp(q.gravityBiasY+x.gravityBiasY,-4,4);q.gravityBiasZ=clamp(q.gravityBiasZ+x.gravityBiasZ,-4,4);q.traversalScale=clamp(q.traversalScale*clamp(x.traversalScale,.1,10),.1,10);q.scannerReliability=clamp(q.scannerReliability*clamp(x.scannerReliability,0,1),0,1);q.scannerContradiction=clamp(q.scannerContradiction+x.scannerContradiction,0,1);q.hazardScale=clamp(q.hazardScale*clamp(x.hazardScale,.1,10),.1,10);}return q;}
std::vector<BoundaryEvent> boundaryEvents(const std::vector<StableId>&a,const std::vector<StableId>&b){std::vector<BoundaryEvent>o;for(auto id:a)if(std::find(b.begin(),b.end(),id)==b.end())o.push_back({id,false});for(auto id:b)if(std::find(a.begin(),a.end(),id)==a.end())o.push_back({id,true});std::sort(o.begin(),o.end(),[](auto&x,auto&y){if(x.regionId!=y.regionId)return x.regionId<y.regionId;return x.entered<y.entered;});return o;}
bool untouchedRequiresSave(const Region&r)noexcept{return r.stateful;}
}
