# Raw-throughput opt-in source inventory.
# Intended function: enumerate throughput-first implementation units for later reconciliation/validation.
set(ELYSIUM_RAW_THROUGHPUT_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/../src/accessibility/CognitiveAssistModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/accessibility/ColorVisionModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/accessibility/InputAssistModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/accessibility/MotionComfortModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/accessibility/SubtitleModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/agriculture/CropGenetics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/agriculture/GeneticsSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/agriculture/HydroponicsSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/agriculture/LivestockSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/agriculture/PestSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/agriculture/PollinationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/agriculture/SeedBank.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/agriculture/SoilSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/BehaviorTree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/CitizenDecision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/CitizenDecisionAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/ColonyGovernorAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/CombatTactics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/CreatureBehavior.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/CreatureBehaviorPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/CrisisResponseAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/DiplomaticNegotiationAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/DiplomaticStrategyAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/EconomyMinisterAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/EspionagePlannerAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/ExplorationPlannerAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/FactionStrategistAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/FleetAdmiralAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/FleetDoctrineAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/GoalUtilityModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/HierarchicalPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/LogisticsDirectorAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/NarrativeDirectorAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/NarrativeOpportunityAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/NavigationIntent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/RaiderAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/ResearchPlannerAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/SettlementDirectorAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/SettlementExpansionAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/SquadCommandAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/SquadCoordinator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/SquadTacticsPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/TradeNegotiationAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/TraderAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/UtilityAi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/WarPlannerAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/WildlifeDirectorAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai/WorkerTaskPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/AIDebugTrace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/AIFailureLearning.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/AIInterrupts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/AgentMemory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/GroupIntent.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/LocationMemory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/PlanBlackboard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/ResourceMemory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/SharedKnowledge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/SocialMemory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/TaskClaimSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ai_memory/ThreatMemory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/anomaly/AnomalyLifecycle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/anomaly/AnomalySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/anomaly/GravityDistortion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/anomaly/RealityContamination.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/anomaly/TemporalDistortion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/AccessibilityAudioCues.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/AcousticPortalSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/AmbienceSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/AmbientAudioSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/AudioEvents.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/AudioOcclusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/BiomeAmbienceAudio.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/CombatAudioSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/DestructionAudioModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/DynamicMusicState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/EmpireAudioSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/ImpactAudioModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/MachineryAudioLayers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/MusicDirector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/RadioCommsAudio.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/RiftAudioSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/SettlementAmbienceAudio.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/SfxRouter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/ShipAudioSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/ShipInteriorAudio.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/SpatialAudioZones.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/VoiceBarkSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/VoiceEventRouter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/audio/VoicePriorityMixer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/AgricultureRobotSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/CircuitNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/CombatDroneAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/ConstructionDroneAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/ControlBus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/DroneFleetSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/FactoryScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/FreightScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/LogicGraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/LogisticsDroneAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/MaintenanceRobotSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/MiningAutomation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/ProgrammableController.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/RemoteControl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/RobotChassisCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/SensorRules.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/SurveyDroneAI.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/automation/WarehouseAutomation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/BioContainment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/CloningSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/CyberneticAugmentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/GeneEditingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/GeneticTraitSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/NanomedicineSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/PathogenEvolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/ProstheticSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/VaccineProgram.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/biotech/XenobiologyResearch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cinematic/CinematicSequenceModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cinematic/ConversationCinematic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cinematic/DeathPresentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cinematic/DiscoveryPresentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cinematic/VictoryPresentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/CareerPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/CelebrationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/ConflictSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/ConversationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/FamilySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/HouseholdSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/MemorySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/MigrationDecision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/MoodSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/NeedSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/PersonalitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/ProfessionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/RelationshipSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/ScheduleSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/SkillProgression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/SocialGroupSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/StressSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/citizens/TraumaSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/CivilizationCohesion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/CivilizationDecline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/CulturalDiffusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/DemographicPressure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/FrontierExpansion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/GoldenAgeCycle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/IndustrialDoctrine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/InstitutionalCapacity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/ResourceDoctrine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/ScientificDoctrine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/TechnologyDiffusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/civilization/UrbanizationModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/climate/ClimateModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/climate/WeatherForecast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/ChildcareService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/CivicBudget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/CivicMaintenance.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/EducationService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/ElderCareService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/ElectionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/EmergencyManagement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/FireDepartment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/HousingMarket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/LaborUnionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/MediaService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/PostalService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/PublicHealthService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/PublicTransit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/PublicTransitService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/RecreationService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/ReligiousService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/RescueService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/SanitationService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/SettlementCensus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/UtilityBilling.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/WasteAuthority.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/WaterAuthority.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/colony/ZoningSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/AbilitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/ArmorPenetration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/ArmorSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/BeamWeaponSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/BoardingCombatSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/BossCombat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/BossPhaseSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/CombatRules.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/CombatStatusEffects.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/CoverSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/ElectronicWarfare.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/EnemyAiPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/EnemyCatalog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/MeleeComboSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/MissileSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/PointDefenseSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/PraetorAbilitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/PraetorBoss.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/ProjectileSimulation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/ShieldSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/ShipWeaponSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/StatusEffectSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/StealthDetection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/SuppressionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/TargetingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/VehicleWeaponSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combat/WeaponSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/ArmorPenetration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/BossPhaseSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/CombatAbilitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/CombatRewardSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/CoverSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/EnergyWeaponSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/GrenadeSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/MeleeComboSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/MoraleCombatSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/RangedBallistics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/ShieldCombatSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/combatx/SuppressionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/DemolitionPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/FoundationPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/HabitatModuleSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/MegastructureProjectSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/OrbitalConstructionPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/RepairPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/StructuralPrefabSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/SurfaceGradingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/TerraformProjectSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/construction/UtilityTrenchPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/AbilityCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/BiomeCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/ContentCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/CreatureCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/CultureCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/DialogueCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/EffectCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/FactionCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/ItemCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/LootTables.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/MaterialCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/PlanetClassCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/QuestCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/RecipeCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/ResearchCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/ShipCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/ShipModuleCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/SpeciesCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/StatusEffectCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/StructureCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/content/WeatherCatalogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/core/ContentExtensions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/core/Diagnostics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/core/JobSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/BlackHoleSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/CometSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/CosmicRadiationWeather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/DeepSpaceSignalSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/GravitationalAnomaly.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/MeteorEventSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/NebulaSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/NeutronStarSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/SolarFlareSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/cosmic/StellarLifecycle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/CourtAudienceSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/CourtCommissionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/CourtFactionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/CourtFavorSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/CourtIntrigueSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/ImperialAuditSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/ImperialLawSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/ImperialSuccessionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/ImperialTaxationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/court/ImperialTitleSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/ArchitectureTraditionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/ArtTraditionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/CuisineTraditionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/CulturalAssimilation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/CulturalRevival.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/FashionTraditionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/LanguageEvolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/MusicTraditionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/MythologySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/culture/SubcultureSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/AIInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/CommandConsoleModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/ContentInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/DebugBookmarkSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/EconomyInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/EntityInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/FrameProfiler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/NetworkInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/SaveInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/SimulationTrace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/SystemProfiler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/devtools/WorldInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/AllianceCohesion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/BorderDisputeSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/CeasefireSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/DiplomaticLeverage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/DiplomaticMission.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/GuaranteeSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/InfluenceNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/MediationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/ProtectorateSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/ReputationPropagation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/SanctionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/diplomacy/TreatyNegotiator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/BlizzardSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/CascadeFailureSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/DustStormSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/EarthquakeSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/FloodSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/HurricaneSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/IndustrialAccidentSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/TsunamiSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/VolcanicSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/disaster/WildfireSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/dungeon/DungeonGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/AquaticEcology.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/ConservationPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/CoralReefSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/DesertificationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/DiseaseVectorEcology.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/ExtinctionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/ForestSuccession.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/HabitatFragmentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/InvasiveSpecies.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/InvasiveSpeciesSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/MigrationCorridor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/NutrientCycle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/OceanFoodWeb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/PollinatorNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/PollinatorSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/PredatorPreyModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/PredatorPreySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/SoilEcology.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/SuccessionModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/TerraformEcology.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/WetlandSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecology/WildlifeHumanConflict.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/AuctionHouse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/BankingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/BlackMarketSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/CommodityFutures.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/CorporateEntitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/CreditLedger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/CreditLoans.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/CreditMarket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/CurrencySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/EconomicShock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/InsuranceContracts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/InsuranceMarket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/LaborMarket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/MarketSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/OwnershipTransfer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/PriceIndex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/PricingModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/PropertyMarket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/RegionalPriceIndex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/SalvageMarket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/SubsidySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/SupplyChainShock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/TariffPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/TariffSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/TaxationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/TradeLeagueSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/WageMarket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/economy/WagePolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/CitizenLifecycle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/CitizenMind.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/CitizenPersistence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/CombatSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/CommandCommitter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/ComponentSnapshots.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/EcsWorld.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/FortressWorkEcs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/GameplayCommandBuffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/InventorySystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/MissionSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/PresentationSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/ResearchSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/SettlementSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/StableIdRegistry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ecs/TravelSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/AncientNetworkSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/ArtifactInvestigation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/DeepCaveExpedition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/DerelictExpedition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/Exploration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/FirstContactSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/GalacticMysterySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/LostColonySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/RiftExpeditionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/SignalInvestigationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/exploration/SurveyExpeditionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/CivilWarSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/CounterintelligenceSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/CourtSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/DiplomaticMissionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/ElectionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/EspionageMissionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/FactionRelations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/IdeologySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/ImperialLaw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/InternalPolitics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/LawSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/LeadershipSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/OccupationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/PropagandaSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/RebellionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/faction/UnswornNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/BoardingOperations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/CarrierOperations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/FleetCommandSuccession.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/FleetFormationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/FleetMoraleSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/FleetReadinessSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/FleetRepairSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/FleetSalvageSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/FleetSupplySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fleet/NavalMineSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/food/CookingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/food/FoodSpoilage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/food/KitchenPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/food/NutritionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/food/RecipeCuisine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/AcceptanceTelemetry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/AgricultureSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/AgricultureWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/AlertInbox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ArcologyProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/AtmosphereGridPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/AutomationSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/AutonomousWork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/AutonomyPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/BehavioralLodWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/CensusSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/CharacterRules.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/Chronicle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ChronicleWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/CitizenSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/CivicWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ConstructionPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ConstructionSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ConstructionWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ContentCatalog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ContractWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/CourtSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/CultureSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/CurfewSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/DataGridPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/DisasterResponse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/DiseaseWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/DistrictSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/DroneSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/DroneWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/EconomySystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/EducationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/EmergencyStockpile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/EmergencyWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/EmpireSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/EmpireWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/EnvironmentSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/EvacuationPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ExplorationSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ExplorationWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/FileKnowledgeSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/FleetSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/FleetWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/FluidGridPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/FoodSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/FortressEcs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/FortressPipeline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/GeologySystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/GovernanceSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/GovernanceWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/HeatGridPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/HistorySystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/HouseholdWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/HousingAllocator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/IncidentWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/IndustrySystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/InfiltrationSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/Inspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/InvestigationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/JobBoard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/JobSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/JusticeWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/LogisticsSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MaintenancePlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MaintenanceWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MechanismSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MedicalSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MedicalWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MegaProjectSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MigrationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MigrationWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MilitaryWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/MonumentSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ObsessionWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/OrbitalElevatorProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/OrbitalLogisticsWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/PermitSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/Persistence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/PlanetaryShieldProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/PoiSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/PopulationSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/PowerGridPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/PrisonSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ProcurementPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ProductionWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ProfessionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/PublicWorks.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/RationPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/RecreationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ResearchSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ResearchWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ReservationLedger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/Retirement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/RetirementWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/RiftGateProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/RoomQualitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SecuritySystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SecurityWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SecurityZoneSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SettlementServices.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ShiftScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ShipyardDistrict.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SiegeWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SimulationScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SiteLifecycle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SkillSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SocialNeeds.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SocialWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/SpaceportSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/StockIndex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/StockpilePolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/StrategicGeneration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/TerraformingProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/ThreatSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/TradeWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/TravelSystems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/TreasurySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/UtilityPriority.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/UtilityWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/VisitorServices.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/VisitorSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/WasteProcessingPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/WorkAssignment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/WorkOrderWorkflow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/WorkOrders.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/WorkforcePlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/fortress/WorldEvents.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/AncientGateNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/AncientRuinsMap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/BinaryStarSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/BlackHoleSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/CometSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/EmpireFrontierModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/GalaxyGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/UniverseFormationFields.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/PlanetCandidateService.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/ResourceDiversityGraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/GalaxyResidency.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/GalaxyResidency.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/JumpNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/NebulaSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/PulsarSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/RegionGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/RoguePlanetSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/SignalPropagation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/StellarEvolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/galaxy/SystemHazardModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/game/Game.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/game/ModeController.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/game/PlaytestTelemetry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/game/SaveSlotManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/game/SessionState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/game/SettingsState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/game/TransitionController.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/game/TutorialSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/AbilitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/AchievementTracker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/ArtifactAttunement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/BiotechEnhancements.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/BlueprintLibrary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/BountySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/BuildingPlacement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/BuildingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/CompanionDrone.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/CompanionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/CraftingQueue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/CraftingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/CyberneticImplants.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/DeconstructionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/DialogueSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/DirectOperativeController.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/DynamicQuestGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/EffectSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/EquipmentSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/ExplorationJournal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/FactionDisguise.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/ImplantSurgeryPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/InteractionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/InventoryTransactions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/LootSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/MiningSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/MissionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/PlayerColonyControl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/PlayerProgression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/ProjectileSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/QuestGraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/QuestObjectives.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/RepairSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/ReputationConsequences.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/RespawnSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/SalvageSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/ScanningSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/SkillProgression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/SurvivalChallengeDirector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/UpgradeTree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gameplay/VehicleInteraction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/AffixSynergySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/ArmorModSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/ArtifactPowerSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/GearRepairSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/GearUpgradeSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/ItemIdentification.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/ItemSocketSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/LootPitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/LootTierSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/SalvageBreakdown.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/SetBonusSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/gear/WeaponModSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/ArtifactProvenance.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/BattleHistorySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/BiographySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/CulturalMemory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/CultureHistory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/DisasterHistorySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/DiscoveryHistory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/DynastyHistory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/DynastySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/EmpireRegisterHistory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/ExplorationHistorySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/GalacticChronicle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/InstitutionHistorySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/LegendSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/MegaprojectHistory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/PersonalLegacy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/RiftHistory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/SettlementChronicle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/SettlementHistorySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/SiteChronicle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/TechnologyHistorySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/TradeHistorySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/history/WarHistory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/AmmunitionIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/CeramicsIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/ChemicalIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/CompositeIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/ElectronicsIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/FactoryLayoutPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/FactorySleepSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/FoodProcessingIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/IndustrialMaintenancePlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/IndustrialQualitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/PharmaceuticalIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/RefineryNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/RoboticsIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/ShipComponentIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/industry/TextileIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/input/InputBindings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/AgricultureEnvironmentBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/ChronicleEventBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/ClaimEmpireBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/CombatLootBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/DroneHaulBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/IndustryItemBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/JusticeOwnershipBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/LogisticsPowerBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/MedicalJobBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/MissionHistoryBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/RemoteSitePromotionBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/ResearchDiscoveryBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/SaveSnapshotBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/StandingTradeBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/StructuralInvalidationBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/TacticalCommandBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/TradeCommitBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/UiCommandBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/VehicleCaravanBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/integration/WeatherSurvivalBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/intelligence/AgentNetworkSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/intelligence/CounterintelligenceSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/intelligence/DeceptionPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/intelligence/HumanIntelligence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/intelligence/IntelArchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/intelligence/IntelFusionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/intelligence/ReconSatelliteSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/intelligence/SignalIntelligence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/inventory/ContainerSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/inventory/DurabilitySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/inventory/EquipmentLoadout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/inventory/HotbarSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/inventory/ItemUpgradeSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/inventory/ReservationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/inventory/TransferPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/localization/LocalizationDatabase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/localization/LocalizationTable.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/localization/NameFormatting.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/localization/ProceduralText.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/CargoContract.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/ColdChain.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/ConvoyAssembly.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/FreightInsurance.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/HazardousCargo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/IntermodalHub.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/LastMileDelivery.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/LogisticsServiceLevel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/PriorityFreight.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/ReturnLogistics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/RouteCapacity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/logistics/WarehouseNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/loot/AffixGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/loot/AffixSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/loot/LootTableResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/loot/ProceduralWeapons.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/loot/UniqueItemSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/main.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/AlloyFoundry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/AmmunitionPlant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/BatteryFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/CeramicFabrication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/CompositeLayup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/DroneAssembly.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/Nanofabrication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/OpticsFabrication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/PharmaceuticalFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/ReactorComponentFactory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/SemiconductorFab.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/manufacturing/ShipyardAssembly.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/medical/DiseaseSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/medical/InjurySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/medical/MedicalSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/medical/PharmacologySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/medical/ProstheticsSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/medical/SurgeryPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/medical/SurgerySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/medical/TriageSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/ArcologyProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/ClimateArrayProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/DeepCoreReactorProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/DysonSwarmProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/InterstellarFoundryProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/OceanHabitatProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/OrbitalRingProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/PlanetaryArchiveProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/PlanetaryShieldProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/SpaceElevatorProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/StargateProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/megaproject/TerraformSpireProject.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/BountyMission.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/ConstructionMission.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/DefenseMission.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/DiplomaticMissionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/DynamicMissionChain.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/EscortMission.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/MissionDirector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/ObjectiveGraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/RecoveryMission.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/RescueMission.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/ResearchMission.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mission/SurveyMission.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/ContentMigration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/ContentNamespace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/ContentPackLoader.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/DataPatchSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/DependencyResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/ModDependencyResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/ModMigrationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/ModRuntime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/ModSaveNamespace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/PermissionModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/SandboxPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/mod/ScriptHooks.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ContentNamespaceRegistry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ContentPatchPlan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/HotReloadPlan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModCapabilityPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModCommandBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModContentOverride.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModDependencyResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModDiagnostics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModEventBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModMigrationRegistry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModPackageIndex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModPermissionModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ModSaveNamespace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/SchemaExtensionRegistry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ScriptBudget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ScriptCommandBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/modding/ScriptEventBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/CrisisArc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/DynamicDialogue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/HistoricalDebate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/LegacySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/MemorialSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/PersonalChronicle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/ProphecySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/RumorNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/SecretSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/SettlementChronicle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/StoryArcDirector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/narrative/WitnessSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/BandwidthBudget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/CapabilityNegotiation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ClientPrediction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/CommandPredictionModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/CommandReplication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/CommandValidation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ConnectionSessionModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/DeltaCompression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/DesyncDiagnostics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/DesyncReport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/EntityReconciliation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/InterestManagement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/LagCompensationContract.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/NetworkSecurityPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/NetworkTime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/PredictionContract.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/PredictionState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ReliableEventStream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ReplicationBaseline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ReplicationDelta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ReplicationInterest.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ReplicationInterestGraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ReplicationPriority.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ReplicationProtocol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/ServerAuthority.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/SessionAuthority.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/SessionMigration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/SessionProtocol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/SnapshotDeltaCodec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/SnapshotInterpolation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/UnreliableStateStream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/network/WorldSnapshotProtocol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/AsteroidSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/DebrisFieldSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/OrbitalConstruction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/OrbitalCustoms.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/OrbitalIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/OrbitalSalvage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/PlanetaryDefenseGrid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/SatelliteNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/ShipyardSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/SpaceTrafficSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/StationConstruction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/orbital/StationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/CharacterCollision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/CharacterMotor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/CollisionWorld.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/DebrisSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/DestructionImpulse.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/ExplosionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/GravityField.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/GravityFrame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/ProjectilePhysics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/RaycastSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/RigidBodyContract.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/SpatialQuery.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/VehicleCollision.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/physics/VehiclePhysics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/AtmosphereProcessor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/DesertGreening.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/FaultStabilization.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/GeoengineeringArray.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/HydrologyEngineer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/MagnetosphereSupport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/OceanRestoration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/PlanetarySurveyGrid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/SoilReclamation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/SurfaceTransitNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/VolcanoManagement.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/planetary/WeatherModification.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/platform/CrashReport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/platform/FileSystemAbstraction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/platform/PlatformServices.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/platform/SaveSlotManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/platform/SessionLifecycle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/platform/SettingsStore.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/platform/ThreadNaming.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/poi/PoiGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/CinematicSequenceModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/CitizenInspectorView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/ColonyOperationsView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/DiplomacyView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/EconomyView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/EnvironmentOverlayView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/FleetCommandView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/HistoryViewerModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/LogisticsHeatmapView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/PhotoModeModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/ResearchTreeView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/presentation/StrategicWarMapView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/AncientMegastructureGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ArchitectureGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ArtTraditionGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ArtifactGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ArtifactLegendGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/BattlefieldGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/CaveBiomeGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/CitizenBackstoryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/CivilizationGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ColonyCrisisGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/CreatureArchetypeGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/CuisineGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/DerelictGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/DiplomaticIncidentGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/DungeonGrammar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/EncounterGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/FactionDoctrineGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/FactionGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/FactionHistoryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/FashionGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/FaunaGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/FestivalGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/FloraGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/HistorySeed.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ImperialFacilityGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/InteriorGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/LanguageGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/LootGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/MonumentGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/NameGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/NameGrammar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/NarrativeBeatGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/PlanetGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/PlantArchetypeGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/PoiGrammar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/QuestChainGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/QuestGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/RaidSiteGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/RegionGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/RiftDungeonGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/RuinHistoryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/RuinsGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/RumorGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/SettlementDistrictGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/SettlementGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/SettlementLayoutGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ShipArchetypeGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ShipGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ShipHistoryGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/ShipNameGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/StationGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/SystemGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/procedural/WarObjectiveGenerator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/AddictionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/BeliefSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/BurnoutSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/GriefSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/IdeologyConflict.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/LeadershipInfluence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/LoyaltySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/MotivationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/RumorSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/psychology/SocialContagion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/AnimationState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/AtmosphereVisuals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/CameraSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/CharacterPresentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/CharacterRenderModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/ChunkRenderScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/ConstructionGhostModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/DamageDecalModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/DetailInstances.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/FleetBattleRenderModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/GpuResourceRegistry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/LightingModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/LodMeshScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/MapOverlayModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/MaterialResolver.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/MegastructureRenderModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/MicroVoxelRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/OcclusionPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/ParticleEvents.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/PlanetAtmosphereRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/PlanetSurfaceRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/PresentationAssets.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/PresentationRuntime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/RaylibGraphicsBackend.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/RenderVisibility.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/RiftRenderModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/SelectionOutlineModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/SettlementRenderModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/ShipRenderModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/VehiclePresentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/VisualBenchmark.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/VoxelDamagePresentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/VoxelMaterialRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/WeatherPresentation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/WeatherRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/render/WorldRenderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/replay/ReplayBookmark.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/replay/ReplayPlayback.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/replay/ReplayRecorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/replay/ReplaySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/research/DiscoverySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/research/ExperimentSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/research/KnowledgeSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/research/LaboratoryPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/research/ResearchRisk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/research/ReverseEngineering.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/research/TechDiffusion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/research/TechTree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/rift/RiftEcology.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/rift/RiftHorrorGrammar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/rift/RiftResearch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/rift/RiftStability.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/rift/RiftTraversal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/rules/CharacterRpg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/BackupRotation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/ChunkDeltaCodec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/CrossShardJournal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/EntitySnapshot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/EntitySnapshotCodec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/IncrementalAutosave.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/RecoverySnapshot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/SaveGenerationManifest.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/SaveIndex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/SaveIntegrityReport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/SaveMigration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/SaveTransactionCoordinator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/SchemaMigrationRegistry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/StrategicStateCodec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/VersionedArchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/save/WorldDeltaCompactor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/ContentCompatibility.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/CrossShardSaveBarrier.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/ReplayBranch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/ReplayCheckpoint.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/ReplayVerification.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/SaveAuditTrail.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/SaveGarbageCollector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/SaveMigrationPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/SaveRecoveryPlan.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/SaveTransactionCoordinator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/StableObjectIndex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/saveinfra/TouchedChunkIndex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/scripting/ScriptCommandQueue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/scripting/ScriptEventApi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/scripting/ScriptEventBus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/scripting/ScriptScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/scripting/ScriptStateStore.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/AccessControlSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/ContrabandInspection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/CounterSabotage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/CybersecuritySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/EvidenceChain.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/IntrusionDetection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/LockdownSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/PrisonerCustody.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/SecureCargoSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/SecurityIncidentLog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/SecurityPatrolPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/security/SecurityZoneSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/HullDamageControl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipBoardingDefense.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipElectronicWarfare.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipFireControl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipLifeSupport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipPointDefense.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipPowerGrid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipRefitPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipRepairQueue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipSalvageOperation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipSensorSuite.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ship/ShipThermalControl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/CompartmentSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/ShipAtmosphereSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/ShipCargoOperations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/ShipCrewSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/ShipDamageControl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/ShipEvacuationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/ShipLifeSupport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/ShipMaintenanceSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/ShipSecuritySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/shipboard/ShipWatchSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/BehavioralLod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/BudgetGovernor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/BudgetScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/CommandScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/DeferredMutationQueue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/DeterminismAudit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/EventRouter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/MacroEconomy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/PhaseOrchestrator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/PopulationAggregate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/RemoteCombat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/RemoteIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/RollbackJournal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/SaveSnapshotPublisher.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/SeasonalTick.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/ShardCoordinator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/ShardPromotion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/SimulationClock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/SimulationPhases.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/SnapshotDiffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/StableCommandQueue.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/StableSequence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/StatePublication.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/StrategicEventScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simulation/WorldEventRouter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/CrossScaleEventBridge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/DeterministicWorkPartition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/InterestBubblePolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/LongHorizonScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/ParallelMergeBarrier.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/PromotionDemotionPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/RemoteAggregateStepper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/SimulationBackpressure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/SimulationHealth.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/SimulationSeedRegistry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/SparseFieldScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/simx/StrategicLODPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/AsteroidBeltSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/CometForecast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/DeepSpaceRelay.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/GravitationalAssist.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/InterstellarBeacon.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/LagrangeInfrastructure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/OrbitalDebris.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/OrbitalTraffic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/RadiationBelts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/SolarSailRoutes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/SpaceWeather.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/stellar/StellarEvolution.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/BlockadeSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/BorderPressure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/CivilizationPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/CivilizationStrategy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/ColonialAdministration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/ColonizationPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/ContractBoard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/DefensePlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/DiplomacySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/DiplomaticMemory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/EmpireStanding.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/EnvoySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/EspionageNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/FederationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/FleetProductionPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/InvasionPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/MilitaryLogisticsPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/PlanetaryGovernment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/PolicySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/RegionalGovernment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/RegionalThreats.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/ReliefMissionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/RemoteSites.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicConstruction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicCrisisManager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicEnergySecurity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicExplorationFleet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicFoodSecurity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicIndustryCapacity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicIntelligence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicMigration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicRaidSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicResearch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicSimulation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/StrategicWarGoals.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/TradeRoutes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/strategy/VassalageSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/survival/ExposureSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/survival/FatigueSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/survival/MetabolismSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/survival/MoraleSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/survival/NutritionQuality.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/survival/SuitLifeSupport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/survival/Survival.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/terraform/AtmosphereTerraforming.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/terraform/BiosphereTerraforming.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/terraform/ClimateEngineering.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/terraform/HydrosphereTerraforming.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/terraform/SoilEngineering.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/terraform/TerraformingRisk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/AIDebugger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/AssetAudit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/ContentValidator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/DeterminismRecorder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/DeterminismTrace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/DeveloperObservability.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/EconomyDebugger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/HistoryDebugger.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/PerformanceBudgetTracker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/PerformanceCounters.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/SaveDiffTool.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/SaveInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/ScenarioSpawner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/SimulationInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/SimulationTrace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/WorldDebugOverlay.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/WorldInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/WorldStateEditor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/tools/WorldgenInspector.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/AirlockTransit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/BoardingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/CapitalShipSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/CargoManifest.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/CargoRailSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/CarrierOperations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ConvoyScheduler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ConvoySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/DockingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/DockingTrafficControl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/DropshipSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ElevatorSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/EmergencyJump.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/FighterWingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/FleetCommand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/FleetLogistics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/FleetTravel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/FlightModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/FuelSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/InterdictionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/InterstellarRoutes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/LaunchWindowPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/MobileBaseShip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/OrbitalInfrastructure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/OrbitalMining.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/OrbitalTransferPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/PassengerTransit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/RefuelPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/RescueMissionPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ShipAtmosphereSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ShipCrewSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ShipDamageControl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ShipInteriorSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ShipModules.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ShipPowerSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ShipThermalSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/ShipTravel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/SpaceHazards.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/SurfaceVehicleRouting.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/TravelPersistence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/TugSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/VehicleModules.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/Vehicles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/travel/WarpSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/AccessibilityModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/BuildMenu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/ChronicleScreen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/CitizenScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/CodexScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/ColonyScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/CommandModels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/CourtScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/CraftingScreen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/CraftingScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/CultureScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/DialogueView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/DiplomacyScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/DroneScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/EmpireScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/FleetCommandScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/FleetScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/FortressDashboard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/FortressPanels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/GalaxyMapModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/HistoryScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/HistoryTimelineModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/HudState.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/IndustryPlannerScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/InspectorModels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/InventoryScreen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/InventoryScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/JobsScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/JusticeScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/MapViewModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/MedicalScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/MegaprojectScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/MissionTracker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/NotificationCenter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/PlanetScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/PoliticsScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/QuestScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/ResearchScreen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/ResearchScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/RiftScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/SettingsScreen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/ShipHud.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/ShipInteriorScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/TacticalOverlay.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/TerraformScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/TradeScreen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/TradeScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/UiViewModels.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/UtilitiesScreenModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/ui/VehicleHud.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/CivilizationView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/EquipmentWorkbenchView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/MegaprojectView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/MissionJournalView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/ModManagerView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/NetworkDiagnosticsView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/ProfilerView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/ReplayView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/SecurityView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/ShipDamageControlView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/ShipyardView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/uix/TerraformingView.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/CyberOperations.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/DemobilizationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/ElectronicWarfare.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/FleetDoctrineSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/GroundDoctrineSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/InsurgencySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/OccupationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/OrbitalBombardmentPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/PlanetaryBlockade.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/PrisonerExchange.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/SiegeLogistics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/StrategicFrontSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/StrategicReserve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/StrategicSupplyLines.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/TheaterCommand.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/WarExhaustion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/WarGoalSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/warfare/WarWeariness.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/wildlife/DomesticationSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/wildlife/EcologyPressure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/wildlife/GeneticsSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/wildlife/MigrationRoutes.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/wildlife/PackBehavior.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/wildlife/PredatorPreyModel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/wildlife/TerritorySystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/wildlife/WildlifeAi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/AtmosphereEngineering.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/BaseBlueprints.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/BaseInfrastructure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/BiomeSuccession.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/BiomeTransitions.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/Block.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/BridgeSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/CargoRailSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/CaveGeneration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ChunkStreamingPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/CivicSimulation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ClaimSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ClimateEngineering.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ConstructionPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/CubeSphere.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/DeepCoreMining.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/DefenseGrid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/Derelict.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/DestructionPolicy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/DroneLogistics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/EcologyRestoration.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/EnvironmentalProtection.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ErosionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/FactorySleepController.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/FireSuppression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/FloraSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/FortressMilitary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/GeologyLayers.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/GeothermalNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/GroundwaterSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/HazardForecast.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/HeatNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/HierarchicalNavigation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ImperialCampaign.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/InfrastructureJournal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/JusticeSecurity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/LandmarkSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/LightEnvironment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/MachineRuntime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/MicroBrick.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/MicroVoxelEditing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/NoiseSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/OceanEngineering.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/OceanSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/OrbitalResourceLink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/OreVeinSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/OutpostNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PipeNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PlanetLodPlanner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PlanetResourceSurvey.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PlanetSettlementIndex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PlanetSurface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PlanetSurfaceMesher.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PlanetaryMiningNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PoiSites.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PollutionSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/PortalNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ProceduralSpecies.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ResourceClaimSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ResourceDepletion.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ResourceProgression.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/RiftExpedition.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/RiverSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/RoadNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/RoomAssignment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SeismicSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SensorNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SettlementClaimMap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SettlementGovernance.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SettlementZones.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SiteContinuity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/StructuralIntegrity.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SurfaceChunkCache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SurfaceChunkPersistence.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SurfaceEnvironment.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SurfaceIndustry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SurfaceInfrastructure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SurfaceItems.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SurfaceNavigation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SurfaceSiege.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/SurfaceWorldRead.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/TerraformingSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/ThreatEcology.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/TunnelNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/UtilityNetwork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/VehiclePathing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/VolcanismSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/VoxelMesher.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/WasteProcessing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/WeatherControl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/WeatherSystem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/World.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/WorldEventSites.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../src/world/WorldMemoryPersistence.cpp
)
