#include "derelict/DerelictInteriorRuntime.hpp"
#include "core/Saturating.hpp"
#include <algorithm>
namespace elysium::derelict {namespace{std::uint64_t mix(std::uint64_t x){x+=0x9e3779b97f4a7c15ULL;x=(x^(x>>30))*0xbf58476d1ce4e5b9ULL;x=(x^(x>>27))*0x94d049bb133111ebULL;return x^(x>>31);}std::uint64_t sid(std::uint64_t site,std::uint64_t domain,std::uint64_t ordinal,std::uint64_t version){auto v=mix(site^mix(domain)^mix(ordinal)^mix(version));return v?v:1;}const ObjectDelta*deltaFor(const DerelictPersistentState&s,std::uint64_t id){auto i=std::find_if(s.objectDeltas.begin(),s.objectDeltas.end(),[&](auto&d){return d.objectStableId==id;});return i==s.objectDeltas.end()?nullptr:&*i;}}
DerelictInterior DerelictInteriorRuntime::generate(std::uint64_t site,std::uint64_t seed,const DerelictKitDef&def,const DerelictPersistentState&persist)const{DerelictInterior o;if(!site||!seed||!def.contentId||!def.generatorVersion||def.sections.empty())return o;o.siteStableId=site;o.kitContentId=def.contentId;o.generatorVersion=def.generatorVersion;std::uint32_t ordinal=0;for(auto&s:def.sections){if(!s.contentId||!s.weight)continue;SectionRecord r{sid(site,0x53454354ULL,ordinal,def.generatorVersion),s.contentId,s.role,s.capabilityMask,ordinal};auto h=mix(seed^r.stableId);r.damaged=(h%100)<25;r.offline=((h>>11)%100)<35;o.sections.push_back(r);++ordinal;}for(std::size_t i=1;i<o.sections.size();++i)o.links.push_back({sid(site,0x4c494e4bULL,i,def.generatorVersion),o.sections[i-1].stableId,o.sections[i].stableId,(mix(seed^i)%5)==0});std::uint64_t oi=0;for(auto&oDef:def.objects){if(!oDef.contentId||o.sections.empty())continue;const auto sec=o.sections[static_cast<std::size_t>(mix(seed^oDef.contentId)%o.sections.size())].stableId;ObjectRecord r{sid(site,0x4f424aULL,oi++,def.generatorVersion),sec,oDef.contentId,oDef.kind,oDef.defaultFlags};if(auto*d=deltaFor(persist,r.stableId)){if(d->tombstoned)continue;r.flags|=d->setFlags;r.flags&=~d->clearFlags;}o.objects.push_back(r);}std::sort(o.objects.begin(),o.objects.end(),[](auto&a,auto&b){return a.stableId<b.stableId;});return o;}
std::vector<SectionRecord>DerelictInteriorRuntime::sectionsWithCapability(const DerelictInterior&i,std::uint64_t m)const{std::vector<SectionRecord>o;for(auto&s:i.sections)if((s.capabilityMask&m)==m)o.push_back(s);return o;}
const ObjectRecord*DerelictInteriorRuntime::findObject(const DerelictInterior&i,std::uint64_t id)const{auto x=std::find_if(i.objects.begin(),i.objects.end(),[&](auto&o){return o.stableId==id;});return x==i.objects.end()?nullptr:&*x;}
bool DerelictInteriorRuntime::applyDelta(DerelictPersistentState&s,ObjectDelta d)const{if(!d.objectStableId)return false;auto i=std::find_if(s.objectDeltas.begin(),s.objectDeltas.end(),[&](auto&x){return x.objectStableId==d.objectStableId;});if(i==s.objectDeltas.end()){s.objectDeltas.push_back(d);return true;}if(d.revision<i->revision)return false;i->setFlags|=d.setFlags;i->clearFlags|=d.clearFlags;i->tombstoned=i->tombstoned||d.tombstoned;i->revision=elysium::safe::saturatingIncrement(std::max(i->revision,d.revision));return true;}
} // namespace elysium::derelict
