// Intended function: encode bounded deterministic replication packets and track acknowledgement state for later authoritative networking.
#include "network/ReplicationProtocol.hpp"
#include <algorithm>
#include <cstring>
namespace elysium{namespace{template<class T>void put(std::vector<std::uint8_t>&o,T v){auto*p=reinterpret_cast<const std::uint8_t*>(&v);o.insert(o.end(),p,p+sizeof(T));}template<class T>bool get(const std::vector<std::uint8_t>&b,std::size_t&i,T&v){if(i+sizeof(T)>b.size())return false;std::memcpy(&v,b.data()+i,sizeof(T));i+=sizeof(T);return true;}}
std::vector<std::uint8_t> encodeReplicationPacket(const ReplicationPacket&p){std::vector<std::uint8_t>o;put(o,p.schema);put(o,p.sessionId);put(o,p.sequence);put(o,p.ackSequence);put(o,p.worldGeneration);std::uint32_t n=std::uint32_t(p.deltas.size());put(o,n);for(auto&d:p.deltas){put(o,d.stableId);put(o,d.archetypeId);put(o,d.revision);put(o,std::uint8_t(d.op));std::uint16_t nf=std::uint16_t(d.fields.size());put(o,nf);for(auto&f:d.fields){put(o,f.fieldId);std::uint32_t z=std::uint32_t(f.bytes.size());put(o,z);o.insert(o.end(),f.bytes.begin(),f.bytes.end());}}return o;}
std::optional<ReplicationPacket> decodeReplicationPacket(const std::vector<std::uint8_t>&b,std::string*e){ReplicationPacket p;std::size_t i=0;std::uint32_t n{};if(!get(b,i,p.schema)||p.schema!=1||!get(b,i,p.sessionId)||!get(b,i,p.sequence)||!get(b,i,p.ackSequence)||!get(b,i,p.worldGeneration)||!get(b,i,n)||n>100000){if(e)*e="invalid packet header";return std::nullopt;}for(std::uint32_t x=0;x<n;++x){EntityReplicationDelta d;std::uint8_t op{};std::uint16_t nf{};if(!get(b,i,d.stableId)||!d.stableId||!get(b,i,d.archetypeId)||!get(b,i,d.revision)||!get(b,i,op)||!get(b,i,nf)){if(e)*e="invalid delta";return std::nullopt;}d.op=ReplicationOp(op);for(std::uint16_t y=0;y<nf;++y){ReplicatedField f;std::uint32_t z{};if(!get(b,i,f.fieldId)||!get(b,i,z)||z>1024*1024||i+z>b.size()){if(e)*e="invalid field";return std::nullopt;}f.bytes.assign(b.begin()+i,b.begin()+i+z);i+=z;d.fields.push_back(std::move(f));}p.deltas.push_back(std::move(d));}return p;}
void ReplicationWindow::noteSent(std::uint64_t s){if(std::find(outstanding_.begin(),outstanding_.end(),s)==outstanding_.end())outstanding_.push_back(s);}
void ReplicationWindow::acknowledge(std::uint64_t s){highestAck_=std::max(highestAck_,s);outstanding_.erase(std::remove_if(outstanding_.begin(),outstanding_.end(),[&](auto x){return x<=s;}),outstanding_.end());}
bool ReplicationWindow::shouldResend(std::uint64_t s)const{return std::find(outstanding_.begin(),outstanding_.end(),s)!=outstanding_.end();}
}
